# standard properties
application_status_standardProperties_all:
  allOf:
    - $ref: "#/application_status_standardProperties_shared"
    - $ref: "#/application_status_standardProperties_adminOnly"

application_status_standardProperties_shared:
  properties:
    id:
      type: integer
      example: 1
    name:
      type: string
      example: Open

application_status_standardProperties_adminOnly:
  allOf:
    - $ref: "#/application_status_standardProperties_shared"



