# standard properties
ApplicationThMatchType_standardProperties_all:
  allOf:
    - $ref: "#/ApplicationThMatchType_standardProperties_shared"


ApplicationThMatchType_standardProperties_shared:
  properties:
    id:
      type: integer
      example: 1
    name:
      type: string
      example: Excellent Fit

