# standard properties
ApplicationStatus_standardProperties_all:
  allOf:
    - $ref: "#/ApplicationStatus_standardProperties_shared"
    - $ref: "#/ApplicationStatus_standardProperties_adminOnly"

ApplicationStatus_standardProperties_shared:
  properties:
    id:
      type: integer
      example: 1
    name:
      type: string
      example: Open

ApplicationStatus_standardProperties_adminOnly:
  allOf:
    - $ref: "#/ApplicationStatus_standardProperties_shared"

# relationship properties


# ApplicationStatus_relationshipProperties_shared:

