# standard properties
application_thMatchType_standardProperties_all:
  allOf:
    - $ref: "#/application_thMatchType_standardProperties_shared"


application_thMatchType_standardProperties_shared:
  properties:
    id:
      type: integer
      example: 1
    name:
      type: string
      example: Excellent Fit

