post:
  description: ""
  operationId: addApplication_proposed
  parameters: 
    - in: path
      name: applications
      # description:
      example: 1234567
      schema:
        type: integer
        format: int32
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties: 
            type: 
              type: string
              example: application
            attributes: 
              type: object
              properties: 
                job: 
                  type: object
                  properties: 
                    id: 
                      type: string
                      example: 123
                memberNumber: 
                  type: object
                  example: 34567
  responses:
    "200":
      content:
        application/json:
          examples:
            example-0001:
              value:
                id: 16492
                status: "1"
          schema:
            properties: {}
            type: object
      description: Item created
  summary: Create application(proposed)
  tags:
    - applications