get:
  operationId: getApplicationEvents
  tags:
    - applications
    - status-proposed
  summary: Get application events (proposed)
  parameters:
    - in: query
      name: filter
      style: deepObject
      allowReserved: true
      explode: true
      schema:
        type: object
        additionalProperties:
          $ref: "../../../components/models/library/applications/ApplicationEvent.yaml#/ApplicationEvents_filter_additionalProperties"
        example:
          application.id: 1
          application.teacher.memberNumber: 1
  responses:
    "200":
      description: successful operation
      content:
        application/json:
          schema:
            $ref: "../../../components/responses/proposed/application-events.yaml#/ApplicationEventsResponse"
    "400":
      description: Invalid ID supplied
    "404":
      description: Application not found
  security:
    - api_key: []

post:
  description: ""
  operationId: postApplicationEvent
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            type:
              type: string
              example: applicationEvent
            attributes:
              allOf:
                - type: object
                - $ref: "../../../components/models/library/applications/ApplicationEvent.yaml#/ApplicationEvent_standardProperties_shared"
                - required:
                    - application
                    - eventType
                    - date
  responses:
    "201":
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  type:
                    type: string
                    example: applicationEvent
                  id:
                    type: string
                    example: 1
      description: Item created
  summary: Create application event (proposed)
  tags:
    - applications
