get:
  operationId: getApplications
  tags:
    - applications
    - status-proposed
  summary: Get list of first 20 applications (proposed)
  parameters:
    - in: path
      name: applicationId
      required: true
      example: 12
      schema:
        type: integer
        format: int32
    - in: query
      name: schema
      required: true
      schema:
        type: string
        enum:
          - admin
          - school
          - teacher
    - in: query
      name: filter
      style: deepObject
      allowReserved: true
      explode: true
      schema:
        type: object
        additionalProperties:
          $ref: "../../../components/models/library/application/application.yaml#/application_standardProperties_all"
          # $ref: "../../../components/schemas/proposed/simple-models/Application.yaml#/ApplicationProperties_all"
        example:
          application: application id, school name, job id
  responses:
    "200":
      description: successful operation
      content:
        application/json:
          schema:
            $ref: "../../../components/responses/proposed/application.yaml#/ApplicationResponse"

    # TODO: move these to a library

    "400":
      description: Invalid id supplied
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: object
                  properties:
                    status:
                      type: string
                      example: "400"
                    title:
                      type: string
                      example: "Invalid id supplied"
                    detail:
                      type: string
                      example: "Id must be and integer"
    "404":
      description: Application not found
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: object
                  properties:
                    status:
                      type: string
                      example: "404"
                    title:
                      type: string
                      example: "Related entity not found"
  security:
    - api_key: []
