get:
  operationId: getApplication
  tags:
    - applications
    - status-proposed
  summary: Get an application (proposed)
  parameters:
    - in: path
      name: applicationId
      required: true
      example: 12
      schema:
        type: integer
        format: int32
    - in: query
      name: schema
      required: true
      schema:
        type: string
        enum:
          - admin
          - school
          - teacher
    - in: query
      name: fields
      style: deepObject
      allowReserved: true
      explode: true
      schema:
        type: object
        additionalProperties:
          $ref: "../../../components/models/library/application/application.yaml#/application_standardProperties_all"
          # $ref: "../../../components/schemas/proposed/simple-models/Application.yaml#/ApplicationProperties_all"
        example:
          application: name,slug,locationLatLong
  responses:
    "200":
      description: successful operation
      content:
        application/json:
          schema:
            $ref: "../../../components/responses/proposed/application.yaml#/ApplicationResponse"

    # TODO: move these to a library

    "400":
      description: Invalid id supplied
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: object
                  properties:
                    status:
                      type: string
                      example: "400"
                    title:
                      type: string
                      example: "Invalid id supplied"
                    detail:
                      type: string
                      example: "Id must be and integer"
    "404":
      description: Application not found
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: object
                  properties:
                    status:
                      type: string
                      example: "404"
                    title:
                      type: string
                      example: "Related entity not found"
  security:
    - api_key: []

post:
  description: ""
  operationId: postApplication
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            type:
              type: string
              example: Application
            attributes:
              allOf:
                - type: object
                - $ref: "../../../components/models/library/application/application.yaml#/application_standardProperties_shared"
                - required:
                    - job
                    - memberNumber

  responses:
    "201":
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  type:
                    type: string
                    example: Application
                  id:
                    type: string
                    example: 2
      description: Item created
  summary: Create application (proposed)
  tags:
    - applications

patch:
  description: Update Application
  operationId: patchApplication
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            type:
              type: string
              example: Application
            attributes:
              allOf:
                - type: object
                - $ref: "../../../components/models/library/application/application.yaml#/application_filter_additionalProperties"

  responses:
    "204":
      content:
        application/json:
          schema:
            type: object
            default: null
      description: Item Updated
  summary: Update application (proposed)
  tags:
    - applications
