patch:
  description: Update Application Event
  operationId: patchApplicationEvent
  parameters:
    - in: path
      name: applicationEventId
      required: true
      example: 1
      schema:
        type: integer
        format: int32
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            type:
              type: string
              example: applicationEvent
            id:
              type: string
              example: 1
            attributes:
              allOf:
                - type: object
                - $ref: "../../../components/models/library/application/ApplicationEvent.yaml#/application-applicationEvent_updatableProperties_shared"

  responses:
    "204":
      content:
        application/json:
          schema:
            type: object
            default: null
      description: Item Updated
  summary: Update application event (proposed)
  tags:
    - applications
# Application_option2:
#   type: object
#   properties:
#     id:
#       type: string
#       example: 1

# Application_option3:
#   application_option3:
#     type: object
#     properties:
#       id:
#         type: string
#         example: 1

