get:
  operationId: getApplication
  tags:
    - applications
    - status-proposed
  summary: Get a application (proposed)
  parameters:
    - in: path
      name: applicationId
      required: true
      example: 12
      schema:
        type: integer
        format: int32
    - in: query
      name: schema
      required: true
      schema:
        type: string
        enum:
          - admin
          - school
          - teacher
    - in: query
      name: fields
      style: deepObject
      allowReserved: true
      explode: true
      schema:
        type: object
        # additionalProperties:
        #   $ref: "../../../components/schemas/proposed/simple-models/Application.yaml#/ApplicationProperties_all"
        example:
          application: name,adminOnlyField1
  responses:
    "200":
      description: successful operation
      # content:
      #   application/json:
      #     schema:
      #       $ref: "../../../components/responses/proposed/application.yaml#/ApplicationResponse"
    "400":
      description: Invalid ID supplied
    "404":
      description: Pet not found
  security:
    - api_key: []
