post:
  description: ""
  operationId: addApplicationEvents_proposed
  parameters: 
    - in: path
      name: applications
      # description:
      example: 1234567
      schema:
        type: integer
        format: int32
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties: 
            type: 
              type: string
              example: applicationEvent
            attributes: 
              type: object
              properties: 
                application: 
                  type: object
                  properties: 
                    id: 
                      type: string
                      example: 123
                eventType: 
                  type: object
                  properties: 
                    id: 
                      type: string
                      example: 3
                date: 
                  type: string
                  format: date-time
                  example: 2011-02-07T15:53:34Z
                notes: 
                  type: string
                  example: Foo bar
                addedDate: 
                  type: string
                  format: date-time
                  example: 2011-02-07T15:53:34Z
  responses:
    "200":
      content:
        application/json:
          examples:
            example-0001:
              value:
                id: 16492
                status: "1"
          schema:
            properties: {}
            type: object
      description: Item created
  summary: Create application events(proposed)
  tags:
    - applications