# See https://redoc.ly/docs/cli/configuration/ for more information.
apis:
  main@v1:
    root: ./openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components:
      severity: warn
    no-sibling-refs:
      severity: error
features.openapi:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#00264B"
      secondary:
        main: "#3FA9B3"
      warning:
        main: "#FF725E"
  generateCodeSamples:
    languages: # Array of language config objects; indicates in which languages to generate code samples.
      - lang: curl # Can be one of the following supported languages: "curl", "Node.js", "JavaScript".
      - lang: "Node.js"
      - lang: "JavaScript"
  expandResponses: all
  hideDownloadButton: true
  jsonSampleExpandLevel: all
  sortPropsAlphabetically: false
  sortTagsAlphabetically: true
