# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi\openapi.yaml:
  path-parameters-defined:
    - >-
      #/paths/~1v1~1teacher~1member-number~1{member-number}~1employment-record~1add/post/parameters
