# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi/components/schemas/proposed/schemas.yaml:
  no-unused-components:
    - "#/SimpleModels"
    - "#/JsonApiModels"
openapi/paths-not-jsonapi/jobs/job-id-update.yaml:
  operation-4xx-response:
    - "#/post/responses"
