# yaml-language-server: $schema=../../../meta/schemas/Path-Singular.json

get:
  operationId: get-application
  tags:
    - application
    - testing-status-1
  summary: Get an application
  parameters:
    - in: path
      name: applicationId
      required: true
      example: 1
      schema:
        type: integer
    - $ref: "../../components/models/json-api/standard/parameters.yaml#/JsonApiModel_parameters_standardSchema"
    - $ref: "../../components/models/json-api/standard/parameters.yaml#/JsonApiModel_parameters_asUserId"

    # - in: query
    #   name: fields
    #   style: deepObject
    #   allowReserved: true
    #   explode: true
    #   schema:
    #     type: object
    #     additionalProperties:
    #       $ref: "../../../components/models/library/application/application.yaml#/application_metaProperties_shared"
    #       # $ref: "../../../components/schemas/proposed/simple-models/Application.yaml#/ApplicationProperties_all"
    #     example:
    #       application: name,slug,locationLatLong
  responses:
    "200":
      description: OK (Request successful)
      content:
        application/json:
          schema:
            $ref: "../../components/responses/application/application.yaml#/Response_application"
    "400":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_400"
    "401":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_401"
    "403":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_403"
    "404":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_404"
    "413":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_413"
    "422":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_422"

patch:
  operationId: patch-application
  tags:
    - application
  summary: Update application
  description: ""
  parameters:
    - in: path
      name: applicationId
      required: true
      example: 1
      schema:
        type: integer
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            type:
              type: string
              example: application
            attributes:
              type: object
              additionalProperties: false
              properties:
                creationDate:
                  type: string
                  format: date-time
                  example: 2011-02-07T15:53:34Z
                latestUpdateDate:
                  type: string
                  format: date-time
                  example: 2011-02-07T15:53:34Z
  responses:
    "204":
      $ref: "../../components/models/json-api/standard/success.yaml#/JsonApiModel_success_204"
    "400":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_400"
    "401":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_401"
    "403":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_403"
    "404":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_404"
    "413":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_413"
    "422":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_422"
