get:
  operationId: getApplicationDataIssues
  tags:
    - application
  summary: Get application data issue
  parameters:
    - in: query
      name: schema
      required: true
      schema:
        type: string
        enum:
          - admin
      description: |
        - admin: only admin can see data issues
    - in: query
      name: filter
      style: deepObject
      allowReserved: true
      explode: true
      schema:
        type: object
        properties:
          filter[application.id]:
            type: number
        example:
          application.id: 1
        required:
          - filter[application.id]

  responses:
    "200":
      description: OK (Request successful)
      content:
        application/json:
          schema:
            $ref: "../../components/responses/application/applicationDataIssues.yaml#/Response_application-applicationDataIssues"
    "400":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_400"
    "401":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_401"
    "403":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_403"
    "404":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_404"
    "413":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_413"
    "422":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_422"
