# yaml-language-server: $schema=../../../meta/schemas/Path-Singular.json

patch:
  operationId: patch-application-applicationEvent
  summary: Update application event
  tags:
    - application
    - testing-status-1
  description: |
    <span class="testing-status-1"></span>
  parameters:
    - in: path
      name: applicationEventId
      required: true
      example: 1
      schema:
        type: integer
    - $ref: "../../components/models/json-api/standard/parameters.yaml#/JsonApiModel_parameters_asUserId"
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            type:
              type: string
              example: application-applicationEvent
            id:
              type: string
              example: "1"
            attributes:
              type: object
              additionalProperties: false
              properties:
                eventType:
                  $ref: "../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_type"
                date:
                  $ref: "../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_date"
                notes:
                  $ref: "../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_notes"
              required:
                - eventType
                - date
          required:
            - type
            - id
            - attributes
  responses:
    "204":
      $ref: "../../components/models/json-api/standard/success.yaml#/JsonApiModel_success_204"
    "400":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_400"
    "401":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_401"
    "403":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_403"
    "404":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_404"
    "413":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_413"
    "422":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_422"

# TODO: add related meta-schema
delete:
  operationId: delete-application-applicationEvent
  summary: Delete an application event
  tags:
    - application
    - testing-status-1
  description: |
    <span class="testing-status-1"></span>
  parameters:
    - in: path
      name: applicationEventId
      required: true
      example: 1
      schema:
        type: integer
    - $ref: "../../components/models/json-api/standard/parameters.yaml#/JsonApiModel_parameters_asUserId"
  responses:
    "204":
      $ref: "../../components/models/json-api/standard/success.yaml#/JsonApiModel_success_204"
    "400":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_400"
    "401":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_401"
    "403":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_403"
    "404":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_404"
    "413":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_413"
    "422":
      $ref: "../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_422"
