# yaml-language-server: $schema=../../../meta/schemas/Path-Singular.json

patch:
  operationId: patchApplicationEvent
  tags:
    - application
  summary: Update application event
  description: ""
  parameters:
    - in: path
      name: applicationEventId
      required: true
      example: 1
      schema:
        type: integer
        format: int32
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            type:
              type: string
              example: application-applicationEvent
            id:
              type: string
              example: "1"
            attributes:
              type: object
              additionalProperties: false
              properties:
                date:
                  $ref: "../../components/models/library/application/ApplicationEvent.yaml#/application-applicationEvent_date"
                notes:
                  $ref: "../../components/models/library/application/ApplicationEvent.yaml#/application-applicationEvent_notes"
  responses:
    "204":
      description: NO_CONTENT (Request successful)
      content:
        application/json:
          schema:
            type: object
            default: null
    "400":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_400"
    "401":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_401"
    "403":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_403"
    "404":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_404"
    "413":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_413"
    "422":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_422"
