get:
  operationId: get-application-applicationEvents
  summary: Get application events
  tags:
    - application
    - testing-status-1
  description: |
    <span class="testing-status-1"></span>
  parameters:
    - in: query
      name: schema
      required: true
      schema:
        type: string
        enum:
          - admin-oneApplication
          - admin-allApplications
          - teacher
      description: |
        - admin-allApplications: use to get all events for a particular teacher
        - admin-oneApplication: use to get all events for a particular application
    - $ref: '../../components/models/json-api/standard/parameters.yaml#/JsonApiModel_parameters_asUserId'
    - in: query
      name: filter
      style: deepObject
      allowReserved: true
      explode: true
      schema:
        type: object
        additionalProperties: false
        properties:
          filter[application.id]:
            type: number
            description: Required unless schema is 'admin-allApplications'
          filter[application.teacher.memberNumber]:
            type: number
            description: Required if schema is 'admin-allApplications'
        example:
          application.id: 1
          application.teacher.memberNumber: 1
  responses:
    '200':
      description: OK (Request successful)
      content:
        application/json:
          schema:
            $ref: '../../components/responses/application/applicationEvents.yaml#/Response_application-applicationEvents'
    '400':
      $ref: '../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_400'
    '401':
      $ref: '../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_401'
    '403':
      $ref: '../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_403'
    '404':
      $ref: '../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_404'
    '413':
      $ref: '../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_413'
    '422':
      $ref: '../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_422'

post:
  operationId: post-application-applicationEvent
  summary: Create application event
  tags:
    - application
    - testing-status-1
  description: |
    <span class="testing-status-1"></span><br/><br/>
    [Simple model](/#tag/simple-model-application-applicationEvent) | 
    [JSON:API model](/#tag/json-api-model-application-applicationEvent)
  parameters:
    - $ref: '../../components/models/json-api/standard/parameters.yaml#/JsonApiModel_parameters_asUserId'
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            data:
              type: object
              properties:
                type:
                  type: string
                  example: application-applicationEvent
                attributes:
                  type: object
                  additionalProperties: false
                  properties:
                    # simple attributes
                    date:
                      $ref: '../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_date'
                    notes:
                      $ref: '../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_notes'
                    # relationship attributes (id only)
                    application:
                      $ref: '../../components/models/json-api/application/application.yaml#/JsonApiModel_application_relationship_attribute_idOnly'
                    type:
                      $ref: '../../components/models/json-api/application/eventType.yaml#/JsonApiModel_application-eventType_relationship_attribute_idOnly'
                    autoEmail:
                      $ref: '../../components/models/json-api/general/autoEmail.yaml#/JsonApiModel_general-autoEmail_relationship_attribute_idOnly'
                  required:
                    - application
                    - type
                    - date
              required:
                - type
                - attributes
          required:
            - data
  responses:
    '201':
      description: CREATED (Request successful)
      content:
        application/json:
          schema:
            $ref: '../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_relationship'
    '400':
      $ref: '../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_400'
    '401':
      $ref: '../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_401'
    '403':
      $ref: '../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_403'
    '404':
      $ref: '../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_404'
    '413':
      $ref: '../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_413'
    '422':
      $ref: '../../components/models/json-api/standard/error.yaml#/JsonApiModel_error_422'
