get:
  operationId: get-application-applicationDataIssues
  tags:
    - application
  summary: Get application data issues
  description: |
    - admin schema: DEPRECATED; non-standard, but exists and is in use
    - admin-v2 schema: 'correct' version of admin schema
    - Process:
      1. [done] mark admin as deprecated
      2. add admin-v2 to the backend (and add related tests)
      3. change front-end to use admin-v2
      4. change admin to be a copy of admin-v2
      5. change front-end to use admin
      6. delete admin-v2
  parameters:
    - in: query
      name: schema
      required: true
      schema:
        type: string
        enum:
          - admin
      description: |
        - admin: only admin can see data issues
    - in: query
      name: filter
      style: deepObject
      allowReserved: true
      explode: true
      schema:
        type: object
        additionalProperties: false
        properties:
          filter[application.id]:
            type: number
        example:
          application.id: 1
        required:
          - filter[application.id]
  responses:
    "200":
      description: OK (Request successful)
      content:
        application/json:
          schema:
            $ref: "../../components/responses/application/applicationDataIssues.yaml#/Response_application-applicationDataIssues"
    "400":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_400"
    "401":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_401"
    "403":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_403"
    "404":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_404"
    "413":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_413"
    "422":
      $ref: "../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_422"
