type: object
properties:
  id:
    type: integer
    format: int32
    example: 1
  name:
    type: string
    example: Info request - update CV
  eventType:
    type: string
    example: {id: 13}
    description: Id 