type: object
properties:
  jobApplicationActions: 
    type: array
    items: 
      type: object
      properties: 
        id: 
          type: integer
          format: int32
          example: 1
        jobApplicationEndStateId: 
          type: integer
          format: int32
          example: 1
        detail: 
          type: string
          example: already interviewed
        actionEndStateDescription: 
          type: string
          example: Proceeded
  jobApplicationStatusForSearch: 
    type: array
    items: 
      type: object
      properties: 
        id: 
          type: integer
          format: int32
          example: -20
        description: 
          type: string
          example: Pending
