SimpleModel_application-action:
  allOf:
    - $ref: "#/SimpleModel_application-action"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application-action_id"
        - $ref: "../../library/application/action.yaml#/application-action_attributes"
        - $ref: "../../library/application/action.yaml#/application-action_relationshipIds"

# shared
SimpleModel_application-action_id:
  properties:
    id:
      type: integer
      format: int32
      example: 1
      readOnly: true
      description: Unique identifier of the object
