SimpleModel_application-applicationEvent:
  oneOf:
    - $ref: "#/SimpleModel_application-applicationEvent_admin"
    - $ref: "#/SimpleModel_application-applicationEvent_school"
    - $ref: "#/SimpleModel_application-applicationEvent_teacher"
  discriminator:
    propertyName: schema
    mapping:
      all: "#/SimpleModel_application-applicationEvent_admin"
      admin: "#/SimpleModel_application-applicationEvent_admin"
      school: "#/SimpleModel_application-applicationEvent_school"
      teacher: "#/SimpleModel_application-applicationEvent_teacher"

SimpleModel_application-applicationEvent_admin:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - admin
    id:
      $ref: "#/SimpleModel_application-applicationEvent_id"
    # simple attributes
    date:
      $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_date"
    creationDate:
      $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_creationDate"
    latestUpdateDate:
      $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_latestUpdateDate"
    notes:
      $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_notes"
    # nameForSchool:
    #   $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_nameForSchool"
    # nameForTeacher:
    #   $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_nameForTeacher"
    # isVisibleToSchool:
    #   $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_isVisibleToSchool"

    # relationship attributes
    applicationId:
      $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_applicationId"
    typeId:
      $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_typeId"
    creationUserId:
      $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_creationUserId"
    latestUpdateUserId:
      $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_latestUpdateUserId"
  required:
    - id
    - date
    - creationDate
    - latestUpdateDate
    - typeId
    - creationUserId
    - latestUpdateUserId

SimpleModel_application-applicationEvent_school:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - school
    id:
      $ref: "#/SimpleModel_application-applicationEvent_id"
    # simple attributes
    date:
      $ref: "../..//library/application/applicationEvent.yaml#/application-applicationEvent_date"
    # relationship attributes
    typeId:
      $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_typeId"
  required:
    - id
    - date
    - typeId

SimpleModel_application-applicationEvent_teacher:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - teacher
    id:
      $ref: "#/SimpleModel_application-applicationEvent_id"
    # simple attributes
    date:
      $ref: "../..//library/application/applicationEvent.yaml#/application-applicationEvent_date"
    # relationship attributes
    typeId:
      $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_typeId"
  required:
    - id
    - date
    - typeId

# shared
SimpleModel_application-applicationEvent_id:
  type: integer
  format: int32
  example: 1
  readOnly: true
  description: Unique identifier of the object
