SimpleModel_application:
  type: object
  properties:
    schema:
      type: string
      example: admin
  discriminator:
    propertyName: schema
    mapping:
      all: "#/SimpleModel_application_all"
      admin: "#/SimpleModel_application_admin"
      adminOnly: "#/SimpleModel_application_adminOnly"
      school: "#/SimpleModel_application_school"
      teacher: "#/SimpleModel_application_teacher"

SimpleModel_application_all:
  allOf:
    - $ref: "#/SimpleModel_application"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application_id"
        - $ref: "../../library/application/application.yaml#/application_standardProperties_all"

SimpleModel_application_admin:
  allOf:
    - $ref: "#/SimpleModel_application"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application_id"
        - $ref: "../../library/application/application.yaml#/application_standardProperties_shared"
        - $ref: "../../library/application/application.yaml#/application_filter_additionalProperties"

SimpleModel_application_adminOnly:
  allOf:
    - $ref: "#/SimpleModel_application"
    - type: object
      allOf:
        - $ref: "../../library/application/application.yaml#/application_filter_additionalProperties"

SimpleModel_application_school:
  allOf:
    - $ref: "#/SimpleModel_application"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application_id"
        - $ref: "../../library/application/application.yaml#/application_standardProperties_shared"

SimpleModel_application_teacher:
  allOf:
    - $ref: "#/SimpleModel_application"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application_id"
        - $ref: "../../library/application/application.yaml#/application_standardProperties_shared"

# shared
SimpleModel_application_id:
  properties:
    id:
      type: integer
      format: int32
      example: 1
      readOnly: true
      description: Unique identifier of the object
