SimpleModel_applicationEventType:
  type: object
  properties:
    schema:
      type: string
      example: admin
  discriminator:
    propertyName: schema
    mapping:
      all: "#/SimpleModel_applicationEventType_all"
      admin: "#/SimpleModel_applicationEventType_admin"
      adminOnly: "#/SimpleModel_applicationEventType_adminOnly"
      school: "#/SimpleModel_applicationEventType_school"
      teacher: "#/SimpleModel_applicationEventType_teacher"

SimpleModel_applicationEventType_all:
  allOf:
    - $ref: "#/SimpleModel_applicationEventType"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_applicationEventType_id"
        - $ref: "../../library/application/ApplicationEventType.yaml#/ApplicationEventType_standardProperties_all"
        - $ref: "../../library/application/ApplicationEventType.yaml#/ApplicationEventType_relationshipProperties_adminOnly"

SimpleModel_applicationEventType_admin:
  allOf:
    - $ref: "#/SimpleModel_applicationEventType"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_applicationEventType_id"
        - $ref: "../../library/application/ApplicationEventType.yaml#/ApplicationEventType_standardProperties_shared"
        - $ref: "../../library/application/ApplicationEventType.yaml#/ApplicationEventType_relationshipProperties_adminOnly"

SimpleModel_applicationEventType_adminOnly:
  allOf:
    - $ref: "#/SimpleModel_applicationEventType"
    - type: object
      allOf:
        - $ref: "../../library/application/ApplicationEventType.yaml#/ApplicationEventType_standardProperties_shared"
        - $ref: "../../library/application/ApplicationEventType.yaml#/ApplicationEventType_relationshipProperties_adminOnly"

SimpleModel_applicationEventType_school:
  allOf:
    - $ref: "#/SimpleModel_applicationEventType"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_applicationEventType_id"
        - $ref: "../../library/application/ApplicationEventType.yaml#/ApplicationEventType_standardProperties_shared"
        # - $ref: "../../library/application/ApplicationEventType.yaml#/ApplicationEventType_relationshipProperties_shared"

SimpleModel_applicationEventType_teacher:
  allOf:
    - $ref: "#/SimpleModel_applicationEventType"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_applicationEventType_id"
        - $ref: "../../library/application/ApplicationEventType.yaml#/ApplicationEventType_standardProperties_shared"
        # - $ref: "../../library/application/ApplicationEventType.yaml#/ApplicationEventType_relationshipProperties_shared"

# shared
SimpleModel_applicationEventType_id:
  properties:
    id:
      type: integer
      format: int32
      example: 1
      readOnly: true
      description: Unique identifier of the object
