SimpleModel_application-applicationEventType:
  type: object
  properties:
    schema:
      type: string
      example: admin
  discriminator:
    propertyName: schema
    mapping:
      all: "#/SimpleModel_application-applicationEventType_all"
      admin: "#/SimpleModel_application-applicationEventType_admin"
      adminOnly: "#/SimpleModel_application-applicationEventType_adminOnly"
      school: "#/SimpleModel_application-applicationEventType_school"
      teacher: "#/SimpleModel_application-applicationEventType_teacher"

SimpleModel_application-applicationEventType_all:
  allOf:
    - $ref: "#/SimpleModel_application-applicationEventType"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application-applicationEventType_id"
        - $ref: "../../library/application/applicationEventType.yaml#/application-applicationEventType_standardProperties_all"
        - $ref: "../../library/application/applicationEventType.yaml#/application-applicationEventType_relationshipProperties_adminOnly"

SimpleModel_application-applicationEventType_admin:
  allOf:
    - $ref: "#/SimpleModel_application-applicationEventType"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application-applicationEventType_id"
        - $ref: "../../library/application/applicationEventType.yaml#/application-applicationEventType_standardProperties_shared"
        - $ref: "../../library/application/applicationEventType.yaml#/application-applicationEventType_relationshipProperties_adminOnly"

SimpleModel_application-applicationEventType_adminOnly:
  allOf:
    - $ref: "#/SimpleModel_application-applicationEventType"
    - type: object
      allOf:
        - $ref: "../../library/application/applicationEventType.yaml#/application-applicationEventType_standardProperties_shared"
        - $ref: "../../library/application/applicationEventType.yaml#/application-applicationEventType_relationshipProperties_adminOnly"

SimpleModel_application-applicationEventType_school:
  allOf:
    - $ref: "#/SimpleModel_application-applicationEventType"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application-applicationEventType_id"
        - $ref: "../../library/application/applicationEventType.yaml#/application-applicationEventType_standardProperties_shared"
        # - $ref: "../../library/application/applicationEventType.yaml#/applicationEventType_relationshipProperties_shared"

SimpleModel_application-applicationEventType_teacher:
  allOf:
    - $ref: "#/SimpleModel_application-applicationEventType"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application-applicationEventType_id"
        - $ref: "../../library/application/applicationEventType.yaml#/application-applicationEventType_standardProperties_shared"
        # - $ref: "../../library/application/applicationEventType.yaml#/applicationEventType_relationshipProperties_shared"

# shared
SimpleModel_application-applicationEventType_id:
  properties:
    id:
      type: integer
      format: int32
      example: 1
      readOnly: true
      description: Unique identifier of the object
