SimpleModel_application_status:
  type: object
  properties:
    schema:
      type: string
      example: admin
  discriminator:
    propertyName: schema
    mapping:
      all: "#/SimpleModel_application_status_all"
      admin: "#/SimpleModel_application_status_admin"
      adminOnly: "#/SimpleModel_application_status_adminOnly"
      school: "#/SimpleModel_application_status_school"
      teacher: "#/SimpleModel_application_status_teacher"

SimpleModel_application_status_all:
  allOf:
    - $ref: "#/SimpleModel_application_status"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application_status_id"
        - $ref: "../../library/applications/ApplicationStatus.yaml#/application_status_standardProperties_all"


SimpleModel_application_status_admin:
  allOf:
    - $ref: "#/SimpleModel_application_status"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application_status_id"
        - $ref: "../../library/applications/ApplicationStatus.yaml#/application_status_standardProperties_shared"
        - $ref: "../../library/applications/ApplicationStatus.yaml#/application_status_standardProperties_adminOnly"


SimpleModel_application_status_adminOnly:
  allOf:
    - $ref: "#/SimpleModel_application_status"
    - type: object
      allOf:
        - $ref: "../../library/applications/ApplicationStatus.yaml#/application_status_standardProperties_adminOnly"


SimpleModel_application_status_school:
  allOf:
    - $ref: "#/SimpleModel_application_status"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application_status_id"
        - $ref: "../../library/applications/ApplicationStatus.yaml#/application_status_standardProperties_shared"


SimpleModel_application_status_teacher:
  allOf:
    - $ref: "#/SimpleModel_application_status"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application_status_id"
        - $ref: "../../library/applications/ApplicationStatus.yaml#/application_status_standardProperties_shared"

# shared
SimpleModel_application_status_id:
  properties:
    id:
      type: integer
      format: int32
      example: 1
      readOnly: true
      description: Unique identifier of the object
