SimpleModel_application-applicationDataIssue:
  type: object
  additionalProperties: false
  properties:
    id:
      $ref: "#/SimpleModel_application-applicationDataIssue_id"
    # simple attributes
    date:
      $ref: "../../library/application/applicationDataIssue.yaml#/application-applicationDataIssue_date"
    #relationship attributes
    applicationId:
      $ref: "../../library/application/applicationDataIssue.yaml#/application-applicationDataIssue_applicationId"
    guidelineId:
      $ref: "../../library/application/applicationDataIssue.yaml#/application-applicationDataIssue_guidelineId"
  required:
    - id
    - date
    - applicationId
    - guidelineId

# shared
SimpleModel_application-applicationDataIssue_id:
      type: integer
      format: int32
      example: 1
      readOnly: true
      description: Unique identifier of the object
