SimpleModel_application:
  allOf:
    - $ref: "#/SimpleModel_application"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application_id"
        - $ref: "../../library/application/application.yaml#/application_attributes"
        - $ref: "../../library/application/application.yaml#/application_relationshipIds"

# shared
SimpleModel_application_id:
  properties:
    id:
      type: integer
      format: int32
      example: 1
      readOnly: true
      description: Unique identifier of the object
