SimpleModel_application_thMatchType:
  type: object
  properties:
    schema:
      type: string
      example: admin
  discriminator:
    propertyName: schema
    mapping:
      all: "#/SimpleModel_application_thMatchType_all"
      admin: "#/SimpleModel_application_thMatchType_admin"
      adminOnly: "#/SimpleModel_application_thMatchType_adminOnly"
      school: "#/SimpleModel_application_thMatchType_school"
      teacher: "#/SimpleModel_application_thMatchType_teacher"

SimpleModel_application_thMatchType_all:
  allOf:
    - $ref: "#/SimpleModel_application_thMatchType"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application_thMatchType_id"
        - $ref: "../../library/applications/ApplicationThMatchType.yaml#/application_thMatchType_standardProperties_all"

SimpleModel_application_thMatchType_admin:
  allOf:
    - $ref: "#/SimpleModel_application_thMatchType"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application_thMatchType_id"
        - $ref: "../../library/applications/ApplicationThMatchType.yaml#/application_thMatchType_standardProperties_shared"

SimpleModel_application_thMatchType_adminOnly:
  allOf:
    - $ref: "#/SimpleModel_application_thMatchType"
    - type: object
      allOf:
        - $ref: "../../library/applications/ApplicationThMatchType.yaml#/application_thMatchType_standardProperties_shared"

SimpleModel_application_thMatchType_school:
  allOf:
    - $ref: "#/SimpleModel_application_thMatchType"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application_thMatchType_id"
        - $ref: "../../library/applications/ApplicationThMatchType.yaml#/application_thMatchType_standardProperties_shared"
        # - $ref: "../../library/applications/application_thMatchType.yaml#/application_thMatchType_relationshipProperties_shared"

SimpleModel_application_thMatchType_teacher:
  allOf:
    - $ref: "#/SimpleModel_application_thMatchType"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application_thMatchType_id"
        - $ref: "../../library/applications/ApplicationThMatchType.yaml#/application_thMatchType_standardProperties_shared"
        # - $ref: "../../library/applications/application_thMatchType.yaml#/application_thMatchType_relationshipProperties_shared"

# shared
SimpleModel_application_thMatchType_id:
  properties:
    id:
      type: integer
      format: int32
      example: 1
      readOnly: true
      description: Unique identifier of the object
