SimpleModel_applicationEvent:
  type: object
  properties:
    schema:
      type: string
      example: admin
  discriminator:
    propertyName: schema
    mapping:
      all: "#/SimpleModel_applicationEvent_all"
      admin: "#/SimpleModel_applicationEvent_admin"
      adminOnly: "#/SimpleModel_applicationEvent_adminOnly"
      school: "#/SimpleModel_applicationEvent_school"
      teacher: "#/SimpleModel_applicationEvent_teacher"

SimpleModel_applicationEvent_all:
  allOf:
    - $ref: "#/SimpleModel_applicationEvent"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_applicationEvent_id"
        - $ref: "../../library/application/ApplicationEvent.yaml#/ApplicationEvent_standardProperties_all"
        - $ref: "../../library/application/ApplicationEvent.yaml#/ApplicationEvent_relationshipProperties_adminOnly"

SimpleModel_applicationEvent_admin:
  allOf:
    - $ref: "#/SimpleModel_applicationEvent"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_applicationEvent_id"
        - $ref: "../../library/application/ApplicationEvent.yaml#/ApplicationEvent_standardProperties_shared"
        - $ref: "../../library/application/ApplicationEvent.yaml#/ApplicationEvent_metaProperties_shared"
        - $ref: "../../library/application/ApplicationEvent.yaml#/ApplicationEvent_relationshipProperties_adminOnly"

SimpleModel_applicationEvent_adminOnly:
  allOf:
    - $ref: "#/SimpleModel_applicationEvent"
    - type: object
      allOf:
        - $ref: "../../library/application/ApplicationEvent.yaml#/ApplicationEvent_metaProperties_shared"
        - $ref: "../../library/application/ApplicationEvent.yaml#/ApplicationEvent_relationshipProperties_adminOnly"

SimpleModel_applicationEvent_school:
  allOf:
    - $ref: "#/SimpleModel_applicationEvent"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_applicationEvent_id"
        - $ref: "../../library/application/ApplicationEvent.yaml#/ApplicationEvent_standardProperties_shared"
        # - $ref: "../../library/application/ApplicationEvent.yaml#/ApplicationEvent_relationshipProperties_shared"

SimpleModel_applicationEvent_teacher:
  allOf:
    - $ref: "#/SimpleModel_applicationEvent"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_applicationEvent_id"
        - $ref: "../../library/application/ApplicationEvent.yaml#/ApplicationEvent_standardProperties_shared"
        # - $ref: "../../library/application/ApplicationEvent.yaml#/ApplicationEvent_relationshipProperties_shared"

# shared
SimpleModel_applicationEvent_id:
  properties:
    id:
      type: integer
      format: int32
      example: 1
      readOnly: true
      description: Unique identifier of the object
