SimpleModel_application-applicationDataIssue:
  type: object
  additionalProperties: false
  properties:
    id:
      $ref: '#/SimpleModel_application-applicationDataIssue_id'
    # simple attributes
    date:
      $ref: '../../library/application/applicationDataIssue.yaml#/application-applicationDataIssue_date'
    name:
      $ref: '../../library/application/applicationDataIssue.yaml#/application-applicationDataIssue_name'
    # relationship attributes
    applicationId:
      $ref: '../../library/application/applicationDataIssue.yaml#/application-applicationDataIssue_applicationId'
    guidelineId:
      $ref: '../../library/application/applicationDataIssue.yaml#/application-applicationDataIssue_guidelineId'
  required:
    - id
    - date
    - name
    - applicationId
    - guidelineId

# shared
SimpleModel_application-applicationDataIssue_id:
  type: integer
  example: 1
  readOnly: true
  description: Unique identifier of the object
