SimpleModel_applicationAction:
  type: object
  properties:
    schema:
      type: string
      example: admin
  discriminator:
    propertyName: schema
    mapping:
      all: "#/SimpleModel_applicationAction_all"
      admin: "#/SimpleModel_applicationAction_admin"
      adminOnly: "#/SimpleModel_applicationAction_adminOnly"
      school: "#/SimpleModel_applicationAction_school"
      teacher: "#/SimpleModel_applicationAction_teacher"

SimpleModel_applicationAction_all:
  allOf:
    - $ref: "#/SimpleModel_applicationAction"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_applicationAction_id"
        - $ref: "../../library/applications/ApplicationAction.yaml#/ApplicationAction_standardProperties_all"
        - $ref: "../../library/applications/ApplicationAction.yaml#/ApplicationAction_relationshipProperties_adminOnly"

SimpleModel_applicationAction_admin:
  allOf:
    - $ref: "#/SimpleModel_applicationAction"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_applicationAction_id"
        - $ref: "../../library/applications/ApplicationAction.yaml#/ApplicationAction_standardProperties_shared"
        - $ref: "../../library/applications/ApplicationAction.yaml#/ApplicationAction_standardProperties_adminOnly"
        - $ref: "../../library/applications/ApplicationAction.yaml#/ApplicationAction_relationshipProperties_adminOnly"

SimpleModel_applicationAction_adminOnly:
  allOf:
    - $ref: "#/SimpleModel_applicationAction"
    - type: object
      allOf:
        - $ref: "../../library/applications/ApplicationAction.yaml#/ApplicationAction_standardProperties_adminOnly"
        - $ref: "../../library/applications/ApplicationAction.yaml#/ApplicationAction_relationshipProperties_adminOnly"

SimpleModel_applicationAction_school:
  allOf:
    - $ref: "#/SimpleModel_applicationAction"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_applicationAction_id"
        - $ref: "../../library/applications/ApplicationAction.yaml#/ApplicationAction_standardProperties_shared"
        # - $ref: "../../library/applications/ApplicationAction.yaml#/ApplicationAction_relationshipProperties_shared"

SimpleModel_applicationAction_teacher:
  allOf:
    - $ref: "#/SimpleModel_applicationAction"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_applicationAction_id"
        - $ref: "../../library/applications/ApplicationAction.yaml#/ApplicationAction_standardProperties_shared"
        # - $ref: "../../library/applications/ApplicationAction.yaml#/ApplicationAction_relationshipProperties_shared"

# shared
SimpleModel_applicationAction_id:
  properties:
    id:
      type: integer
      format: int32
      example: 1
      readOnly: true
      description: Unique identifier of the object
