SimpleModel_application-applicationEvent:
  allOf:
    - $ref: "#/SimpleModel_application-applicationEvent"
    - type: object
      allOf:
        - $ref: "#/SimpleModel_application-applicationEvent_id"
        - $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_attributes"
        - $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_relationshipIds"

# shared
SimpleModel_application-applicationEvent_id:
  properties:
    id:
      type: integer
      format: int32
      example: 1
      readOnly: true
      description: Unique identifier of the object
