openapi: 3.1.0
info:
  version: 1.0.0
  title: Teacher Horizons API
  contact:
    email: dev@teacherhorizons.com
    url: "http://127.0.0.1:8080/"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "https://www.teacherhorizons.com/assets/bird/logo.png"
  description:
    # TODO: figure out how to disable this warning (e.g. 'yamllint disable-line' doesn't work)
    $ref: "./info-description.md"
# externalDocs:
#   description: Find out how to create a GitHub repo for your OpenAPI definition.
#   url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  # categories (alphabetical)
  - name: admin-notes
    description: Operations relating to admin-notes
  - name: applications
    description: Operations relating to applications
  - name: cities
    description: Operations relating to cities
  - name: community-responses
    description: Operations relating to community responses
  - name: countries
    description: Operations relating to countries
  - name: documents
    description: Operations relating to documents
  - name: email-templates
    description: Operations relating to email templates
  - name: employment-records
    description: Operations relating to teacher employment records
  - name: general
    description: General Operations
  - name: job-applications
    description: Operations relating to job applications
  - name: jobs
    description: Operations relating to jobs
  - name: lists
    description: Operations relating to simple lists of objects - such as subjects or roles
  - name: other
    description: Other Operations
  - name: references
    description: Operations relating to references
  - name: regional-regions
    description: Operations relating to regions (~continents)
  - name: schools
    description: Operations relating to schools
  - name: teachers
    description: Operations relating to teachers or candidates
  - name: users
    description: Operations relating to users

  # statuses
  - name: status-current
    description: ...
  - name: status-proposed
    description: ...

  # non-th-examples
  - name: Example - Echo
    description: Example echo operations.
  - name: Example - User
    description: Operations about users.
  - name: Example - Tag
    description: This is a tag description.

  - name: simple-model-application-applicationEvent
    x-displayName: Simple model - application-applicationEvent
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_application-applicationEvent" />

  - name: simple-model-application-applicationEventType
    x-displayName: Simple model - application-applicationEventType
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_application-applicationEventType" />

  - name: simple-model-application-action
    x-displayName: Simple model - application-action
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_application-action" />

  - name: simple-model-application-status
    x-displayName: Simple model - application-status
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_application-status" />

  - name: simple-model-application-thMatchType
    x-displayName: Simple model - application-thMatchType
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_application-thMatchType" />

  - name: simple-model-city
    x-displayName: Simple model - City
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_city" />

  - name: simple-model-country
    x-displayName: Simple model - Country
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_country" />

  - name: simple-model-general-educationlevel
    x-displayName: Simple model - general-educationLevel
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_general-educationLevel" />

  - name: simple-model-pensionScheme-type
    x-displayName: Simple model - PensionSchemeType
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_pensionSchemeType" />

  - name: simple-model-currency
    x-displayName: Simple model - Currency
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_currency" />

  - name: simple-model-lists
    x-displayName: Lists
    description: |
      ### AcademicSystem
      <SchemaDefinition schemaRef="#/components/schemas/AcademicSystem" />
      ### Accreditation
      <SchemaDefinition schemaRef="#/components/schemas/Accreditation" />
      ### ThDiscoveryMethod
      <SchemaDefinition schemaRef="#/components/schemas/ThDiscoveryMethod" />
      ### ThDiscoveryMethodCategory
      <SchemaDefinition schemaRef="#/components/schemas/ThDiscoveryMethodCategory" />

  - name: simple-model-pet
    x-displayName: Pet (Non-TH)
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Pet" />

  - name: simple-model-regional-region
    x-displayName: Simple model - regional-region
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_regional-region" />

  - name: simple-model-school
    x-displayName: School
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/School" />

  - name: simple-model-teacher
    x-displayName: Simple model - Teacher
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_teacher" />

  # JSON:API models

  - name: json-api-model-application-action
    x-displayName: JSON:API model - application-action
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_application-action" />

  - name: json-api-model-application-applicationEvent
    x-displayName: JSON:API model - application-applicationEvent
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_application-applicationEvent" />

  - name: json-api-model-application-status
    x-displayName: JSON:API model - application-status
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_application-status" />

  - name: json-api-model-city
    x-displayName: JSON:API model - City
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_city" />

  - name: json-api-model-country
    x-displayName: JSON:API model - Country
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_country" />

  - name: json-api-model-regional-region
    x-displayName: JSON:API model - regional-region
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_regional-region" />

  - name: json-api-model-teacher
    x-displayName: JSON:API model - Teacher
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_teacher" />

  - name: json-api-model-application-thMatchType
    x-displayName: JSON:API model - application-thMatchType
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_application-thMatchType" />

x-tagGroups:
  - name: Simple models
    tags:
      - simple-model-accreditation-type
      - simple-model-application-action
      - simple-model-application-applicationEvent
      - simple-model-application-applicationEventType
      - simple-model-application-status
      - simple-model-application-thMatchType
      - simple-model-city
      - simple-model-country
      - simple-model-currency
      - simple-model-general-educationLevel
      - simple-model-lists
      - simple-model-pensionScheme-type
      - simple-model-pet
      - simple-model-regional-region
      - simple-model-school
      - simple-model-teacher

  - name: JSON:API models
    tags:
      - json-api-model-application-action
      - json-api-model-application-applicationEvent
      - json-api-model-application-status
      - json-api-model-application-thMatchType
      - json-api-model-city
      - json-api-model-country
      - json-api-model-regional-region
      - json-api-model-teacher

  - name: API
    tags:
      - admin-notes
      - applications
      - cities
      - community-responses
      - countries
      - documents
      - email-templates
      - employment-records
      - general
      - job-applications
      - jobs
      - lists
      - other
      - references
      - regional-regions
      - schools
      - sites
      - teachers
      - users

  - name: API - non-TH examples
    tags:
      - Example - Echo
      - Example - User
      - Example - Tag
servers:
  - url: "https://beta.teacherhorizons.com/th/api"
paths:
  $ref: "./paths/paths.yaml"

components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "http://example.com/api/oauth/dialog"
          scopes:
            "read:users": read users info
            "write:users": modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
  schemas:
    $ref: "./components/schemas/proposed/schemas.yaml"
