openapi: 3.1.0
info:
  version: 1.0.0
  title: Teacher Horizons API
  contact:
    email: dev@teacherhorizons.com
    url: "http://127.0.0.1:8080/"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "https://www.teacherhorizons.com/assets/bird/logo.png"
  description:
    # TODO: figure out how to disable this warning (e.g. 'yamllint disable-line' doesn't work)
    $ref: "./info-description.md"
# externalDocs:
#   description: Find out how to create a GitHub repo for your OpenAPI definition.
#   url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  # tags - categories (alphabetical)
  - name: admin-notes
    description: Operations relating to admin-notes
  - name: applications
    description: Operations relating to applications
  - name: cities
    description: Operations relating to cities
  - name: community-responses
    description: Operations relating to community responses
  - name: countries
    description: Operations relating to countries
  - name: documents
    description: Operations relating to documents
  - name: email-templates
    description: Operations relating to email templates
  - name: employment-records
    description: Operations relating to teacher employment records
  - name: general
    description: General Operations
  - name: job-applications
    description: Operations relating to job applications
  - name: jobs
    description: Operations relating to jobs
  - name: lists
    description: Operations relating to simple lists of objects - such as subjects or roles
  - name: other
    description: Other Operations
  - name: references
    description: Operations relating to references
  - name: regional-regions
    description: Operations relating to regions (~continents)
  - name: schools
    description: Operations relating to schools
  - name: teachers
    description: Operations relating to teachers or candidates
  - name: users
    description: Operations relating to users

  # tags - statuses
  - name: status-current
    description: ...
  - name: status-proposed
    description: ...

  # tags - non-th-examples
  - name: Example - Echo
    description: Example echo operations.
  - name: Example - User
    description: Operations about users.
  - name: Example - Tag
    description: This is a tag description.

  # tags - simple-models

  # tags - simple-models - application
  - name: simple-model-application
    x-displayName: Simple model - application
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_application" />

  - name: simple-model-application-applicationEvent
    x-displayName: Simple model - application-applicationEvent
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_application-applicationEvent" />

  - name: simple-model-application-eventType
    x-displayName: Simple model - application-eventType
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_application-eventType" />

  - name: simple-model-application-action
    x-displayName: Simple model - application-action
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_application-action" />

  - name: simple-model-application-status
    x-displayName: Simple model - application-status
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_application-status" />

  - name: simple-model-application-thMatchType
    x-displayName: Simple model - application-thMatchType
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_application-thMatchType" />

  # tags - simple-models - general
  - name: simple-model-general-educationLevel
    x-displayName: Simple model - general-educationLevel
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_general-educationLevel" />

  - name: simple-model-general-pensionSchemeType
    x-displayName: Simple model - general-pensionSchemeType
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_general-pensionSchemeType" />

  - name: simple-model-general-religion
    x-displayName: Simple model - general-religion
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_general-religion" />

  - name: simple-model-general-role
    x-displayName: Simple model - general-role
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_general-role" />

  - name: simple-model-general-roleType
    x-displayName: Simple model - general-roleType
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_general-roleType" />

  - name: simple-model-general-subjectGroup
    x-displayName: Simple model - general-subjectGroup
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_general-subjectGroup" />

  - name: simple-model-general-subject
    x-displayName: Simple model - general-subject
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_general-subject" />

  - name: simple-model-general-currency
    x-displayName: Simple model - general-currency
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_general-currency" />

  - name: simple-model-lists-academicSystem
    x-displayName: Simple model - lists-academicSystem
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_lists-academicSystem" />

  - name: simple-model-general-worldLanguage
    x-displayName: Simple model - general-worldLanguage
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_general-worldLanguage" />

  # - name: simple-model-lists
  #   x-displayName: Lists
  #   description: |
  #     ### AcademicSystem
  #     <SchemaDefinition schemaRef="#/components/schemas/AcademicSystem" />


  #     ### Accreditation
  #     <SchemaDefinition schemaRef="#/components/schemas/Accreditation" />
  #     ### ThDiscoveryMethod
  #     <SchemaDefinition schemaRef="#/components/schemas/ThDiscoveryMethod" />
  #     ### ThDiscoveryMethodCategory
  #     <SchemaDefinition schemaRef="#/components/schemas/ThDiscoveryMethodCategory" />

  # - name: simple-model-pet
  #   x-displayName: Pet (Non-TH)
  #   description: |
  #     <SchemaDefinition schemaRef="#/components/schemas/Pet" />

  # tags - simple-models - regional
  - name: simple-model-regional-city
    x-displayName: Simple model - regional-city
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_city" />

  - name: simple-model-regional-country
    x-displayName: Simple model - regional-country
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_country" />

  - name: simple-model-regional-region
    x-displayName: Simple model - regional-region
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_regional-region" />

  # tags - simple-models - school
  - name: simple-model-school
    x-displayName: School
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/School" />

  - name: simple-model-school-academicSystem
    x-displayName: Simple model - school-academicSystem
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_school-academicSystem" />

  - name: simple-model-school-communityQuestion
    x-displayName: Simple model - school-communityQuestion
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_school-communityQuestion" />

  - name: simple-model-school-curriculumType
    x-displayName: Simple model - school-curriculumType
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_school-curriculumType" />

  - name: simple-model-school-facility
    x-displayName: Simple model - school-facility
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_school-facility" />

  # tags - simple-models - teacher
  - name: simple-model-teacher
    x-displayName: Simple model - teacher
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/SimpleModel_teacher" />

  # JSON:API models

  # tags - JSON:API models - application
  - name: json-api-model-application-action
    x-displayName: JSON:API model - application-action
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_application-action" />

  - name: json-api-model-application
    x-displayName: JSON:API model - application
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_application" />

  - name: json-api-model-application-applicationEvent
    x-displayName: JSON:API model - application-applicationEvent
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_application-applicationEvent" />

  - name: json-api-model-application-eventType
    x-displayName: JSON:API model - application-eventType
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_application-eventType" />

  - name: json-api-model-application-status
    x-displayName: JSON:API model - application-status
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_application-status" />

  - name: json-api-model-application-thMatchType
    x-displayName: JSON:API model - application-thMatchType
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_application-thMatchType" />

  # tags - JSON:API models - general
  - name: json-api-model-general-currency
    x-displayName: JSON:API model - general-currency
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_general-currency" />

  - name: json-api-model-general-educationLevel
    x-displayName: JSON:API model - general-educationLevel
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_general-educationLevel" />

  - name: json-api-model-general-pensionSchemeType
    x-displayName: JSON:API model - general-pensionSchemeType
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_general-pensionSchemeType" />

  - name: json-api-model-general-religion
    x-displayName: JSON:API model - general-religion
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_general-religion" />

  - name: json-api-model-general-role
    x-displayName: JSON:API model - general-role
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_general-role" />

  - name: json-api-model-general-roleType
    x-displayName: JSON:API model - general-roleType
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_general-roleType" />

  - name: json-api-model-general-subject
    x-displayName: JSON:API model - general-subject
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_general-subject" />

  - name: json-api-model-general-subjectGroup
    x-displayName: JSON:API model - general-subjectGroup
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_general-subjectGroup" />

  - name: json-api-model-general-worldLanguage
    x-displayName: JSON:API model - general-worldLanguage
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_general-worldLanguage" />

  # tags - JSON:API models - regional
  - name: json-api-model-city
    x-displayName: JSON:API model - regional-city
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_city" />

  - name: json-api-model-country
    x-displayName: JSON:API model - regional-country
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_country" />

  - name: json-api-model-regional-region
    x-displayName: JSON:API model - regional-region
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_regional-region" />

  # tags - JSON:API models - teacher
  - name: json-api-model-teacher
    x-displayName: JSON:API model - teacher
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_teacher" />

  # tags - JSON:API models - school
  - name: json-api-model-school-academicSystem
    x-displayName: JSON:API model - school-academicSystem
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_school-academicSystem" />

  - name: json-api-model-school-communityQuestion
    x-displayName: JSON:API model - school-communityQuestion
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_school-communityQuestion" />

  - name: json-api-model-school-curriculumType
    x-displayName: JSON:API model - school-curriculumType
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_school-curriculumType" />

  - name: json-api-model-school-facility
    x-displayName: JSON:API model - school-facility
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/JsonApiModel_school-facility" />

x-tagGroups:
  - name: Simple models
    tags:
      # - simple-model-lists
      # - simple-model-pet
      # - simple-model-accreditation-type
      - simple-model-application-action
      - simple-model-application
      - simple-model-application-applicationEvent
      - simple-model-application-eventType
      - simple-model-application-status
      - simple-model-application-thMatchType
      - simple-model-general-currency
      - simple-model-general-educationLevel
      - simple-model-general-pensionSchemeType
      - simple-model-general-religion
      - simple-model-general-role
      - simple-model-general-roleType
      - simple-model-general-subject
      - simple-model-general-subjectGroup
      - simple-model-general-worldLanguage
      - simple-model-regional-city
      - simple-model-regional-country
      - simple-model-regional-region
      - simple-model-school
      - simple-model-school-academicSystem
      - simple-model-school-communityQuestion
      - simple-model-school-curriculumType
      - simple-model-school-facility
      - simple-model-teacher

  - name: JSON:API models
    tags:
      - json-api-model-application
      - json-api-model-application-action
      - json-api-model-application-applicationEvent
      - json-api-model-application-eventType
      - json-api-model-application-status
      - json-api-model-application-thMatchType
      - json-api-model-general-currency
      - json-api-model-general-educationLevel
      - json-api-model-general-pensionSchemeType
      - json-api-model-general-religion
      - json-api-model-general-role
      - json-api-model-general-roleType
      - json-api-model-general-subject
      - json-api-model-general-subjectGroup
      - json-api-model-general-worldLanguage
      - json-api-model-regional-city
      - json-api-model-regional-country
      - json-api-model-regional-region
      - json-api-model-school-academicSystem
      - json-api-model-school-communityQuestion
      - json-api-model-school-curriculumType
      - json-api-model-school-facility
      - json-api-model-teacher

  - name: API
    tags:
      - admin-notes
      - applications
      - cities
      - community-responses
      - countries
      - documents
      - email-templates
      - employment-records
      - general
      - job-applications
      - jobs
      - lists
      - other
      - references
      - regional-regions
      - schools
      - sites
      - teachers
      - users

  - name: API - non-TH examples
    tags:
      - Example - Echo
      - Example - User
      - Example - Tag
servers:
  - url: "https://beta.teacherhorizons.com/th/api"
paths:
  $ref: "./paths/paths.yaml"

components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "http://example.com/api/oauth/dialog"
          scopes:
            "read:users": read users info
            "write:users": modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
  schemas:
    $ref: "./components/schemas/proposed/schemas.yaml"
