# attributes
application-applicationDataIssue_date:
  type: string
  format: date-time
  example: 2011-02-07T15:53:35Z

# relationship attributes
application-applicationDataIssue_applicationId:
  type: integer
  example: 1
  description: Relationship to application_dataissue

application-applicationDataIssue_guidelineId:
  type: integer
  example: 1
  description: Relationship to application_dataissue
