# simple attributes

application-applicationEvent_date:
  type: string
  format: date-time
  example: 2011-02-07T15:53:34Z
  description: |
    <span class="website"></span>

application-applicationEvent_notes:
  type: string
  nullable: true
  description: <span class="website"></span> Main
  example: Foo bar
  maxLength: 1000

application-applicationEvent_creationDate:
  type: string
  format: date-time
  example: 2011-02-07T15:53:34Z
  description: |
    <span class="website"></span>

application-applicationEvent_latestUpdateDate:
  type: string
  format: date-time
  example: 2011-02-07T15:53:34Z
  description: |
    <span class="website"></span>

# relationship attributes
application-applicationEvent_applicationId:
  type: integer
  example: 1
  description: |
    <span class="website"></span> 
    <span class="dw"></span>
    Relationship to [application](/#tag/simple-model-application)

application-applicationEvent_typeId:
  type: integer
  example: 1
  description: |
    <span class="website"></span> <span class="dw"></span> Relationship to [application-eventType](/#tag/simple-model-application-eventType)

application-applicationEvent_emailId:
  type: integer
  example: 1
  description: |
    Relationship to [general-autoEmail ](/#tag/simple-model-general-autoEmail ) #check with RR

application-applicationEvent_creationUserId:
  type: integer
  example: 1
  description: |
    <span class="website"></span> 
    <span class="dw"></span>
    Relationship to [user](/#tag/simple-model-user)

application-applicationEvent_latestUpdateUserId:
  type: integer
  example: 1
  description: |
    <span class="website"></span> Relationship to [user](/#tag/simple-model-user)
