#attributes
application_recommendationText:
  type: string
  nullable: true
  example: Lorem ipsum
  description: Main
  maxLength: 10000

application_creationDate:
  type: string
  format: date-time
  example: 2011-02-07T15:53:35Z

application_submissionToSchoolDate:
  type: string
  format: date-time
  example: 2011-02-07T15:53:35Z

application_latestUpdateDate:
  type: string
  format: date-time
  example: 2011-02-07T15:53:35Z

application_hasDataIssues:
  type: boolean
  example: true

application_thSystemMatchScore:
  description: System match score of teacher and job, value between 0 and 1
  type: number
  nullable: true
  format: double
  example: 0.75

# relationship attributes
application_jobId:
  type: integer
  example: 1
  description: |
    Relationship to [job](/#tag/simple-model-job)

application_teacherId:
  type: integer
  example: 1
  description: |
    Relationship to [teacher](/#tag/simple-model-teacher)

application_creationUserId:
  type: integer
  example: 1
  description: |
    Relationship to [user](/#tag/simple-model-user)

application_latestUpdateUserId:
  type: integer
  example: 1
  description: |
    Relationship to [user](/#tag/simple-model-user)

application_statusId:
  type: integer
  example: 1
  description: |
    Relationship to [application-status](/#tag/simple-model-application-status)

application_latestEventId:
  type: integer
  example: 1
  description: |
    Relationship to [application-applicationEvent](/#tag/simple-model-application-applicationEvent)

application_thMatchTypeId:
  type: integer
  example: 1
  description: |
    Relationship to [application-thMatchType](/#tag/simple-model-application-thMatchType)

# relationships
application_job:
  additionalProperties: false
  type: object
  properties:
    id:
      type: string
      example: '1'
      description: |
        Relationship to [job](/#tag/simple-model-job)
  required:
    - id

application_teacher:
  type: object
  additionalProperties: false
  properties:
    id:
      type: string
      example: '1'
      description: |
        Relationship to [teacher](/#tag/simple-model-teacher)
  required:
    - id

application_creationUser:
  type: object
  additionalProperties: false
  properties:
    id:
      type: string
      example: '1'
      description: |
        Relationship to [user](/#tag/simple-model-user)
  required:
    - id

application_latestUpdateUser:
  type: object
  additionalProperties: false
  properties:
    id:
      type: string
      example: '1'
      description: |
        Relationship to [user](/#tag/simple-model-user)
  required:
    - id

application_status:
  type: object
  additionalProperties: false
  properties:
    id:
      type: string
      example: '1'
      description: |
        Relationship to [application-status](/#tag/simple-model-application-status)
  required:
    - id

application_latestEvent:
  type: object
  additionalProperties: false
  properties:
    id:
      type: string
      example: '1'
      description: |
        Relationship to [application-applicationEvent](/#tag/simple-model-application-applicationEvent)
  required:
    - id

application_thMatchType:
  type: object
  additionalProperties: false
  properties:
    id:
      type: string
      example: '1'
      description: |
        Relationship to [application-thMatchType](/#tag/simple-model-application-thMatchType)
  required:
    - id
