# attributes
application-applicationEvent_date:
  type: string
  format: date-time
  example: 2011-02-07T15:53:34Z

application-applicationEvent_notes:
  type: string
  nullable: true
  example: Foo bar

application-applicationEvent_creationDate:
  type: string
  format: date-time
  example: 2011-02-07T15:53:34Z

application-applicationEvent_latestUpdateDate:
  type: string
  format: date-time
  example: 2011-02-07T15:53:34Z

# application-applicationEvent_nameForSchool:
#   type: string
#   nullable: true
#   example:

# application-applicationEvent_nameForTeacher:
#   type: string
#   nullable: true
#   example:

# application-applicationEvent_isVisibleToSchool:
#   type: boolean
#   nullable: true
#   example:  1

application-applicationEvent_applicationId:
  type: integer
  example: 1
  description: Relationship to application

application-applicationEvent_typeId:
  type: integer
  example: 1
  description: Relationship to application_eventType

application-applicationEvent_emailId:
  type: integer
  example: 1
  description: Relationship to general_emails

application-applicationEvent_creationUserId:
  type: integer
  example: 1
  description: Relationship to User

application-applicationEvent_latestUpdateUserId:
  type: integer
  example: 1
  description: Relationship to User

# relationships
application-applicationEvent_application:
  type: object
  additionalProperties: false
  properties:
    id:
      type: string
      example: "1"
      description: ""
  required:
    - id

application-applicationEvent_type:
  type: object
  additionalProperties: false
  properties:
    id:
      type: string
      example: "1"
      description: Relationship to ..
  required:
    - id

application-applicationEvent_creationUser:
  type: object
  additionalProperties: false
  properties:
    id:
      type: string
      example: "1"
      description: Relationship to User
  required:
    - id

application-applicationEvent_latestUpdateUser:
  type: object
  additionalProperties: false
  properties:
    id:
      type: string
      example: "1"
      description: Relationship to User
  required:
    - id

application-applicationEvent_email:
  type: object
  additionalProperties: false
  properties:
    id:
      type: string
      example: "1"
      description: Relationship to ..
  required:
    - id
