# standard properties
application_standardProperties_all:
  allOf:
    - $ref: "#/application_standardProperties_shared"

application_standardProperties_shared:
  properties:
      job: 
          type: object
          properties: 
            id: 
              type: string
              example: 123
      memberNumber: 
          type: object
          example: 34567

application_filter_additionalProperties:
  properties:
      thMatchType: 
          type: object
          properties: 
            id: 
              type: string
              example: 2
      recommendationText: 
          type: object
          example: Foo bar

application-application_metaProperties_shared:
  properties:
    creationDate:
      type: string
      format: date-time
      example: 2011-02-07T15:53:34Z
    latestUpdateDate:
      type: string
      format: date-time
      example: 2011-02-07T15:53:34Z

#relationship properties
application-applicationEvent_relationshipProperties_adminOnly:
  properties:
    creationUserId:
      type: integer
      example: 1
      description: Relationship to User
    latestUpdateUserId:
      type: integer
      example: 1
      description: Relationship to User

# jobId
# teacherId
# statusId
