# standard properties
application-applicationEventType_standardProperties_all:
  allOf:
    - $ref: "#/application-applicationEventType_standardProperties_shared"

application-applicationEventType_standardProperties_shared:
  properties:
    id:
      type: integer
      example: 1
    name:
      type: string
      example: Info request from Candidate

#relationship properties
application-applicationEventType_relationshipProperties_adminOnly:
  properties:
    applicationStatusId:
      type: integer
      example: 1
      description: Relationship to application-status
