# simple attributes
application-applicationDataIssue_date:
  type: string
  nullable: true
  format: date-time
  example: 2011-02-07T15:53:35Z
  description: |
    <span class="website"></span>

application-applicationDataIssue_name:
  type: string
  description: Main, Name of the related guideline (non-standard json-api)
  example: Lorem ipsum

# relationship attributes
application-applicationDataIssue_applicationId:
  type: integer
  example: 1
  description: |
    <span class="website"></span> Relationship to [application](/#tag/simple-model-application)

application-applicationDataIssue_guidelineId:
  type: integer
  example: 1
  description: |
    <span class="website"></span> Relationship to [application-guideline](/#tag/simple-model-application-guideline)
