# standard properties
application_standardProperties_all:
  allOf:
    - $ref: "#/application_standardProperties_shared"

application_standardProperties_shared:
  properties:
    job:
      type: object
      properties:
        id:
          type: string
          example: "1"
    memberNumber:
      type: number
      example: 34567

application_filter_additionalProperties:
  properties:
    thMatchType:
      type: object
      properties:
        id:
          type: string
          example: "1"
    recommendationText:
      type: object
      example: Foo bar
