application-applicationEvent_filter_additionalProperties:
  allOf:
    - $ref: "#/application-applicationEvent_properties_date"
# attributes
application-applicationEvent_attributes:
  allOf:
    - $ref: "#/application-applicationEvent_properties_date"
    - $ref: "#/application-applicationEvent_properties_notes"
    - $ref: "#/application-applicationEvent_properties_creationDate"
    - $ref: "#/application-applicationEvent_properties_latestUpdateDate"

# relationshipIds
application-applicationEvent_relationshipIds:
  allOf:
    - $ref: "#/application-applicationEvent_properties_applicationId"
    - $ref: "#/application-applicationEvent_properties_typeId"
    - $ref: "#/application-applicationEvent_properties_emailId"
    - $ref: "#/application-applicationEvent_properties_creationUserId"
    - $ref: "#/application-applicationEvent_properties_latestUpdateUserId"

# attribute relationships
application-applicationEvent_attributeRelationships:
  allOf:
    - $ref: "#/application-applicationEvent_properties_application"
    - $ref: "#/application-applicationEvent_properties_type"
    - $ref: "#/application-applicationEvent_properties_email"

# relationships
# TODO - not yet used; consider referring to the json-api user model here, and then trying to use
application-applicationEvent_relationships:
  allOf:
    - $ref: "#/application-applicationEvent_properties_creationUser"
    - $ref: "#/application-applicationEvent_properties_latestUpdateUser"

# properties
application-applicationEvent_properties_date:
  properties:
    date:
      $ref: "#/application-applicationEvent_date"

application-applicationEvent_properties_notes:
  properties:
    notes:
      $ref: "#/application-applicationEvent_notes"

application-applicationEvent_properties_creationDate:
  properties:
    creationDate:
      $ref: "#/application-applicationEvent_creationDate"

application-applicationEvent_properties_latestUpdateDate:
  properties:
    latestUpdateDate:
      $ref: "#/application-applicationEvent_latestUpdateDate"

application-applicationEvent_properties_applicationId:
  properties:
    applicationId:
      $ref: "#/application-applicationEvent_applicationId"

application-applicationEvent_properties_typeId:
  properties:
    typeId:
      $ref: "#/application-applicationEvent_typeId"

application-applicationEvent_properties_emailId:
  properties:
    emailId:
      $ref: "#/application-applicationEvent_emailId"

application-applicationEvent_properties_creationUserId:
  properties:
    creationUserId:
      $ref: "#/application-applicationEvent_creationUserId"

application-applicationEvent_properties_latestUpdateUserId:
  properties:
    latestUpdateUserId:
      $ref: "#/application-applicationEvent_latestUpdateUserId"

application-applicationEvent_properties_application:
  properties:
    application:
      $ref: "#/application-applicationEvent_application"

application-applicationEvent_properties_email:
  properties:
    email:
      $ref: "#/application-applicationEvent_email"

application-applicationEvent_properties_type:
  properties:
    eventType:
      $ref: "#/application-applicationEvent_type"

application-applicationEvent_properties_creationUser:
  properties:
    creationUser:
      $ref: "#/application-applicationEvent_creationUser"

application-applicationEvent_properties_latestUpdateUser:
  properties:
    latestUpdateUser:
      $ref: "#/application-applicationEvent_latestUpdateUser"

# attributes
application-applicationEvent_date:
  type: string
  format: date-time
  example: 2011-02-07T15:53:34Z

application-applicationEvent_notes:
  type: string
  example: Foo bar

application-applicationEvent_creationDate:
  type: string
  format: date-time
  example: 2011-02-07T15:53:34Z

application-applicationEvent_latestUpdateDate:
  type: string
  format: date-time
  example: 2011-02-07T15:53:34Z

application-applicationEvent_applicationId:
  type: integer
  example: 1
  description: Relationship to application

application-applicationEvent_typeId:
  type: integer
  example: 1
  description: Relationship to application_eventType

application-applicationEvent_emailId:
  type: integer
  example: 1
  description: Relationship to general_emails

application-applicationEvent_creationUserId:
  type: integer
  example: 1
  description: Relationship to User

application-applicationEvent_latestUpdateUserId:
  type: integer
  example: 1
  description: Relationship to User

application-applicationEvent_application:
  type: object
  properties:
    id:
      type: string
      example: "1"

application-applicationEvent_email:
  type: object
  properties:
    id:
      type: string
      example: "1"

application-applicationEvent_type:
  type: object
  properties:
    id:
      type: string
      example: "1"

application-applicationEvent_creationUser:
  type: object
  properties:
    id:
      type: string
      example: "1"
  description: Relationship to User

application-applicationEvent_latestUpdateUser:
  type: object
  properties:
    id:
      type: string
      example: "1"
  description: Relationship to User
