# TODO RR+AS: figure out how best to name the groups of properties (try listing individual properties and groups)

# standard properties
application-applicationEvent_standardProperties_all:
  allOf:
    - $ref: "#/application-applicationEvent_standardProperties_shared"
    - $ref: "#/application-applicationEvent_metaProperties_shared"
    - $ref: "#/application-applicationEvent_updatableProperties_shared"

application-applicationEvent_standardProperties_shared:
  properties:
    id:
      type: integer
      example: 1

application-applicationEvent_metaProperties_shared:
  properties:
    creationDate:
      type: string
      format: date-time
      example: 2011-02-07T15:53:34Z
    latestUpdateDate:
      type: string
      format: date-time
      example: 2011-02-07T15:53:34Z

application-applicationEvent_updatableProperties_shared:
  properties:
    date:
      type: string
      format: date-time
      example: 2011-02-07T15:53:34Z
    notes:
      type: string
      example: Foo bar

application-applicationEvent_date:
  type: string
  format: date-time
  example: 2011-02-07T15:53:34Z

application-applicationEvent_notes:
  type: string
  example: Foo bar

application-applicationEvent_properties_date:
  properties:
    date:
      type: string
      format: date-time
      example: 2011-02-07T15:53:34Z

application-applicationEvent_properties_notes:
  properties:
    notes:
      type: string
      example: Foo bar

Application_option4:
  properties:
    application:
      type: object
      properties:
        id:
          type: string
          example: 1
    email:
      type: object
      properties:
        id:
          type: string
          example: 1
    eventType:
      type: object
      properties:
        id:
          type: string
          example: 1

#filter properties
application-applicationEvent_filter_additionalProperties:
  type: object
  description: Direct attributes
  properties:
    application.id:
      type: number
      example: 1
    application.teacher.memberNumber:
      type: number
      example: 123456

#relationship properties
application-applicationEvent_relationshipProperties_adminOnly:
  properties:
    applicationId:
      type: integer
      example: 1
      description: Relationship to application
    eventTypeId:
      type: integer
      example: 1
      description: Relationship to application_eventType
    emailId:
      type: integer
      example: 1
      description: Relationship to general_emails
    creationUserId:
      type: integer
      example: 1
      description: Relationship to User
    latestUpdateUserId:
      type: integer
      example: 1
      description: Relationship to User

application-applicationEvent_post_request_option1:
  properties:
    date:
      type: string
      format: date-time
      example: 2011-02-07T15:53:34Z
    notes:
      type: string
      example: Foo bar

application-applicationEvent_post_request_option2:
  properties:
    date:
      $ref: "#/application-applicationEvent_date"
    notes:
      $ref: "#/application-applicationEvent_notes"

application-applicationEvent_post_request_option3:
  allOf:
    - $ref: "#/application-applicationEvent_properties_date"
    - $ref: "#/application-applicationEvent_properties_notes"

application-applicationEvent_post_200:
  allOf:
    - $ref: "#/application-applicationEvent_properties_date"

application-applicationEvent_post_404:
  allOf:
    - $ref: "#/application-applicationEvent_properties_notes"
