# attributes
application-applicationEvent_date:
  type: string
  format: date-time
  example: 2011-02-07T15:53:34Z

application-applicationEvent_notes:
  type: string
  nullable: true
  description: Main
  example: Foo bar

application-applicationEvent_creationDate:
  type: string
  format: date-time
  example: 2011-02-07T15:53:34Z

application-applicationEvent_latestUpdateDate:
  type: string
  format: date-time
  example: 2011-02-07T15:53:34Z

# relationship attributes
application-applicationEvent_applicationId:
  type: integer
  example: 1
  description: Relationship to application

application-applicationEvent_typeId:
  type: integer
  example: 1
  description: Relationship to application-eventType

application-applicationEvent_emailId:
  type: integer
  example: 1
  description: Relationship to general-email

application-applicationEvent_creationUserId:
  type: integer
  example: 1
  description: Relationship to user

application-applicationEvent_latestUpdateUserId:
  type: integer
  example: 1
  description: Relationship to user

# relationships
application-applicationEvent_application:
  type: object
  additionalProperties: false
  properties:
    id:
      type: string
      example: "1"
      description: Relationship to application
  required:
    - id

application-applicationEvent_type:
  type: object
  additionalProperties: false
  properties:
    id:
      type: string
      example: "1"
      description: Relationship to application-eventType
  required:
    - id

application-applicationEvent_email:
  type: object
  additionalProperties: false
  properties:
    id:
      type: string
      example: "1"
      description: Relationship to general-email
  required:
    - id

application-applicationEvent_creationUser:
  type: object
  additionalProperties: false
  properties:
    id:
      type: string
      example: "1"
      description: Relationship to user
  required:
    - id

application-applicationEvent_latestUpdateUser:
  type: object
  additionalProperties: false
  properties:
    id:
      type: string
      example: "1"
      description: Relationship to user
  required:
    - id
