# standard properties
application-applicationEvent_standardProperties_all:
  allOf:
    - $ref: "#/application-applicationEvent_standardProperties_shared"
    - $ref: "#/application-applicationEvent_metaProperties_shared"
    - $ref: "#/application-applicationEvent_updatableProperties_shared"

application-applicationEvent_standardProperties_shared:
  properties:
    id:
      type: integer
      example: 1

application-applicationEvent_metaProperties_shared:
  properties:
    creationDate:
      type: string
      format: date-time
      example: 2011-02-07T15:53:34Z
    latestUpdateDate:
      type: string
      format: date-time
      example: 2011-02-07T15:53:34Z

application-applicationEvent_updatableProperties_shared:
  properties:
    date:
      type: string
      format: date-time
      example: 2011-02-07T15:53:34Z
    notes:
      type: string
      example: Foo bar

#filter properties
application-applicationEvent_filter_additionalProperties:
  type: object
  description: Direct attributes
  properties:
    application.id:
      type: number
      example: 1
    application.teacher.memberNumber:
      type: number
      example: 123456

#relationship properties
application-applicationEvent_relationshipProperties_adminOnly:
  properties:
    applicationId:
      type: integer
      example: 1
      description: Relationship to application
    eventTypeId:
      type: integer
      example: 1
      description: Relationship to application_eventType
    emailId:
      type: integer
      example: 1
      description: Relationship to general_emails
    creationUserId:
      type: integer
      example: 1
      description: Relationship to User
    latestUpdateUserId:
      type: integer
      example: 1
      description: Relationship to User
