# standard properties
ApplicationAction_standardProperties_all:
  allOf:
    - $ref: "#/ApplicationAction_standardProperties_adminOnly"

ApplicationAction_standardProperties_adminOnly:
  properties:
    detail:
      type: string
      example: already interviewed
    politeEmailMessage:
      type: string
      example: Thank you for contacting

# relationship properties

ApplicationAction_relationshipProperties_adminOnly:
  properties:
    endStateId:
      type: integer
      example: 1
      description: Relationship to State
    emailId:
      type: integer
      example: xyz@gmail.com
      description: Relationship to Email
