job-application-statuses:
  deprecated: true
  name: job-application-statuses
  in: query
  description: Comma separated list of job application status ids; TODO - better if called job-application-status-ids
  example: -20,-10,1
  schema:
    type: string
