get:
  tags:
    - Job applications
    - status-todo
  summary: Get a list of job applications
  parameters:
    - $ref: '../../components/parameters/school.yaml#/school-ids'

    - $ref: '../../components/parameters/job.yaml#/job-ids'
    - $ref: '../../components/parameters/job.yaml#/job-subjects'

    - $ref: '../../components/parameters/teacher.yaml#/member-numbers'

    - $ref: '../../components/parameters/job-application.yaml#/job-application-statuses'
    - $ref: '../../components/parameters/job-application.yaml#/actioned-by-user-ids'

    - $ref: '../../components/parameters/list.yaml#/limit'
    - $ref: '../../components/parameters/list.yaml#/page-number'
    - $ref: '../../components/parameters/list.yaml#/sort'
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            anyOf:
              - $ref: '../../components/schemas/job-applications/for-admin/response.yaml'
              - $ref: '../../components/schemas/job-applications/for-school/response.yaml'
              - $ref: '../../components/schemas/job-applications/for-teacher/response.yaml'
            discriminator:
              propertyName: apiSchema
              mapping:
                JobApplicationsForAdminSet1: '../../components/schemas/job-applications/for-admin/response.yaml'
                JobApplicationsForSchoolSet1: '../../components/schemas/job-applications/for-school/response.yaml'
                JobApplicationsForTeacherSet1: '../../components/schemas/job-applications/for-teacher/response.yaml'
    '400':
      description: Invalid ID supplied
    '404':
      description: Pet not found
  security:
    - api_key: []
