JsonApiModel_application-action:
  type: object
  properties:
    type:
      $ref: "#/JsonApiModel_application-action_type"
    id:
      $ref: "#/JsonApiModel_application-action_id"
    attributes:
      allOf:
        - $ref: "../../library/application/action.yaml#/application-action_attributes"
    relationships:
      $ref: "#/JsonApiModel_application-action_relationships"
      attributes:
        allOf:
          $ref: "../../library/application/action.yaml#/application-action_relationships"
  required:
    - type
    - id

JsonApiModel_application-action_relationships:
  type: object
  description: Related Attributes
  properties:
    endState:
      $ref: "../../../schemas/proposed/simple-models/helpers/json-api.yaml#/RelToOne"
    email:
      $ref: "../../../schemas/proposed/simple-models/helpers/json-api.yaml#/RelToOne"

JsonApiModel_application-action_type:
  type: string
  example: application-action
  description: application-action
  readOnly: true

JsonApiModel_application-action_id:
  type: string
  example: "1"
  readOnly: true
  description: Unique identifier of the application-action (string)
