JsonApiModel_application-action:
  type: object
  properties:
    type:
      $ref: "#/JsonApiModel_application-action_type"
    id:
      $ref: "#/JsonApiModel_application-action_id"
    attributes:
      type: object
      # works
      # properties:
      #   detail:
      #     type: string
      #     example: already interviewed
      #   politeEmailMessage:
      #     type: string
      #     example: foo bar

      # works
      # properties:
      #   detail:
      #     $ref: "../../library/application/action.yaml#/application-action_detail"
      #   politeEmailMessage:
      #     $ref: "../../library/application/action.yaml#/application-action_politeEmailMessage"

      # works
      # allOf:
      #   - properties:
      #       detail:
      #         type: string
      #         example: already interviewed
      #       politeEmailMessage:
      #         type: string
      #         example: foo bar

      # works
      # allOf:
      #   - properties:
      #       detail:
      #         $ref: "../../library/application/action.yaml#/application-action_detail"
      #       politeEmailMessage:
      #         $ref: "../../library/application/action.yaml#/application-action_politeEmailMessage"

      # works
      # allOf:
      #   - $ref: "#/foo"

      # works
      # allOf:
      #   - $ref: "#/foo"
      #   - $ref: "#/bar"

      # dosen't work ('Recursive')
      allOf:
        - $ref: "../../library/application/action.yaml#/application-action_properties_detail"
        - $ref: "#/bar"

      # - $ref: "../../library/application/action.yaml#/application-action_properties_detail"

      # - $ref: "../../library/application/action.yaml#/application-action_politeEmailMessage"
      # allOf:
      #   - $ref: "../../library/application/action.yaml#/application-action_attributes"
    relationships:
      $ref: "#/JsonApiModel_application-action_relationships"
      # attributes:
      #   allOf:
      #     $ref: "../../library/application/action.yaml#/application-action_relationships"
  required:
    - type
    - id

foo:
  properties:
    detail:
      $ref: "../../library/application/action.yaml#/application-action_detail"

bar:
  properties:
    politeEmailMessage:
      $ref: "../../library/application/action.yaml#/application-action_politeEmailMessage"

JsonApiModel_application-action_relationships:
  type: object
  description: Related Attributes
  properties:
    endState:
      $ref: "../../../schemas/proposed/simple-models/helpers/json-api.yaml#/RelToOne"
    email:
      $ref: "../../../schemas/proposed/simple-models/helpers/json-api.yaml#/RelToOne"

#
JsonApiModel_application-action_type:
  type: string
  example: application-action
  description: application-action
  readOnly: true

JsonApiModel_application-action_id:
  type: string
  example: "1"
  readOnly: true
  description: Unique identifier of the application-action (string)
JsonApiModel_application-actionType_type:
  type: string
  example: application-actionType
  description: application-actionType
  readOnly: true

JsonApiModel_application-actionType_id:
  type: string
  example: "1"

JsonApiModel_application-actionType_relationship_attribute:
  type: object
  properties:
    id:
      $ref: "#/JsonApiModel_application-actionType_id"

JsonApiModel_application-actionType_relationship:
  type: object
  properties:
    data:
      type: object
      properties:
        type:
          $ref: "#/JsonApiModel_application-actionType_type"
        id:
          $ref: "#/JsonApiModel_application-actionType_id"
