JsonApiModel_application-action:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: "#/JsonApiModel_application-action_type"
    id:
      $ref: "#/JsonApiModel_application-action_id"
    attributes:
      type: object
      additionalProperties: false
      properties:
        #simple attributes
        detail:
          $ref: "../../library/application/action.yaml#/application-action_detail"
        politeEmailMessage:
          $ref: "../../library/application/action.yaml#/application-action_politeEmailMessage"
        #relationship attributes
        endState:
          $ref: "../../library/application/action.yaml#/application-action_endState"
          #endState - check with Ryan
        email:
          $ref: "../general/autoEmail.yaml#/JsonApiModel_general-autoEmail_relationship_attribute"
    relationships:
      type: object
      additionalProperties: false
      properties:
        endState:
          $ref: "../../../schemas/proposed/simple-models/helpers/json-api.yaml#/RelToOne"
          #endState - check with Ryan
        email:
          $ref: "../general/autoEmail.yaml#/JsonApiModel_general-autoEmail_relationship"
  required:
    - type
    - id

# type, id and relationship
JsonApiModel_application-action_type:
  type: string
  example: application-action
  description: Unique identifier of the entity type
  readOnly: true

JsonApiModel_application-action_id:
  type: string
  example: "1"
  readOnly: true
  description: Unique identifier of the entity (string)


JsonApiModel_application-actionType_relationship_attribute:
  type: object
  additionalProperties: false
  properties:
    id:
      $ref: "#/JsonApiModel_application-action_id"
  required:
    - id

JsonApiModel_application-action_relationship:
  type: object
  additionalProperties: false
  properties:
    data:
      type: object
      additionalProperties: false
      properties:
        type:
          $ref: "#/JsonApiModel_application-action_type"
        id:
          $ref: "#/JsonApiModel_application-action_id"
      required:
        - type
        - id
  required:
    - data
