JsonApiModel_application-applicationEvent:
  type: object
  properties:
    schema:
      type: string
      example: admin
  discriminator:
    propertyName: schema
    mapping:
      admin: "#/JsonApiModel_application-applicationEvent_admin"
      school: "#/JsonApiModel_application-applicationEvent_school"
      teacher: "#/JsonApiModel_application-applicationEvent_teacher"

JsonApiModel_application-applicationEvent_admin:
  allOf:
    - $ref: "#/JsonApiModel_application-applicationEvent"
    - type: object
    - properties:
        $ref: "#/JsonApiModel_application-applicationEvent_attributes_admin"
    - required:
        - type
        - id

JsonApiModel_application-applicationEvent_school:
  allOf:
    - $ref: "#/JsonApiModel_application-applicationEvent"
    - type: object
    - properties:
        $ref: "#/JsonApiModel_application-applicationEvent_attributes_school"
    - required:
        - type
        - id

JsonApiModel_application-applicationEvent_teacher:
  allOf:
    - $ref: "#/JsonApiModel_application-applicationEvent"
    - type: object
    - properties:
        $ref: "#/JsonApiModel_application-applicationEvent_attributes_school"
    - required:
        - type
        - id

# admin
JsonApiModel_application-applicationEvent_attributes_admin:
  type:
    $ref: "#/JsonApiModel_application-applicationEvent_type"
  id:
    $ref: "#/JsonApiModel_application-applicationEvent_id"
  attributes:
    allOf:
      - $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_standardProperties_all"
      - $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_wip"
      # - $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_standardProperties_shared"
      # - $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_metaProperties_shared"
      # - $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_updatableProperties_shared"
      # - $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_standardProperties_adminOnly"
  relationships:
    $ref: "#/JsonApiModel_application-applicationEvent_relationships_admin"

JsonApiModel_application-applicationEvent_relationships_admin:
  type: object
  description: Related attributes
  properties:
    creationUser:
      $ref: "../../../schemas/proposed/simple-models/helpers/json-api.yaml#/RelToOne"
    latestUpdateUser:
      $ref: "../../../schemas/proposed/simple-models/helpers/json-api.yaml#/RelToOne"

# school
JsonApiModel_application-applicationEvent_attributes_school:
  type:
    $ref: "#/JsonApiModel_application-applicationEvent_type"
  id:
    $ref: "#/JsonApiModel_application-applicationEvent_id"
  # attributes:
  #   allOf:
  # - $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_standardProperties_shared"
  # relationships:

# teacher
JsonApiModel_application-applicationEvent_attributes_teacher:
  type:
    $ref: "#/JsonApiModel_application-applicationEvent_type"
  id:
    $ref: "#/JsonApiModel_application-applicationEvent_id"
  attributes:
    allOf:
      # - $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_standardProperties_shared"
  # relationships:

# shared
JsonApiModel_application-applicationEvent_type:
  type: string
  example: application-applicationEvent
  description: application-applicationEvent
  readOnly: true

JsonApiModel_application-applicationEvent_id:
  type: string
  example: "1"
  readOnly: true
  description: Unique identifier of the application-applicationEvent (string)

JsonApiModel_application-applicationEvent_relationship:
  type: object
  properties:
    data:
      type: object
      properties:
        type:
          $ref: "#/JsonApiModel_application-applicationEvent_type"
        id:
          $ref: "#/JsonApiModel_application-applicationEvent_id"
