# yaml-language-server: $schema=../../../../../meta/JsonApiModel-MultipleSchemas.json

JsonApiModel_application:
  oneOf:
    - $ref: "#/JsonApiModel_application_admin"
    - $ref: "#/JsonApiModel_application_school"
    - $ref: "#/JsonApiModel_application_teacher"
  discriminator:
    propertyName: schema
    mapping:
      admin: "#/JsonApiModel_application_admin"
      school: "#/JsonApiModel_application_school"
      teacher: "#/JsonApiModel_application_teacher"

JsonApiModel_application_admin:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - admin
    type:
      $ref: "#/JsonApiModel_application_type"
    id:
      $ref: "#/JsonApiModel_application_id"
    attributes:
      type: object
      additionalProperties: false
      properties:
        # simple attributes
        creationDate:
          $ref: "../../library/application/application.yaml#/application_creationDate"
        submissionToSchoolDate:
          $ref: "../../library/application/application.yaml#/application_submissionToSchoolDate"
        latestUpdateDate:
          $ref: "../../library/application/application.yaml#/application_latestUpdateDate"
        recommendationText:
          $ref: "../../library/application/application.yaml#/application_recommendationText"
        thSystemMatchScore:
          $ref: "../../library/application/application.yaml#/application_thSystemMatchScore"
        hasDataIssues:
          $ref: "../../library/application/application.yaml#/application_hasDataIssues"
        # relationship attributes
        job:
          $ref: "../job/job.yaml#/JsonApiModel_job_relationship_attribute"
        teacher:
          $ref: "../teacher/teacher.yaml#/JsonApiModel_teacher_relationship_attribute"
        creationUser:
          $ref: "../user/user.yaml#/JsonApiModel_user_relationship_attribute"
        latestUpdateUser:
          $ref: "../user/user.yaml#/JsonApiModel_user_relationship_attribute"
        status:
          $ref: "../application/status.yaml#/JsonApiModel_application-status_relationship_attribute"
        latestEvent:
          $ref: "../application/ApplicationEvent.yaml#/JsonApiModel_application-applicationEvent_relationship_attribute"
        thMatchType:
          $ref: "../application/thMatchType.yaml#/JsonApiModel_application-thMatchType_relationship_attribute"
    relationships:
      type: object
      additionalProperties: false
      properties:
        job:
          $ref: "../job/job.yaml#/JsonApiModel_job_relationship"
        teacher:
          $ref: "../teacher/teacher.yaml#/JsonApiModel_teacher_relationship"
        creationUser:
          $ref: "../user/user.yaml#/JsonApiModel_user_relationship"
        latestUpdateUser:
          $ref: "../user/user.yaml#/JsonApiModel_user_relationship"
        status:
          $ref: "../application/status.yaml#/JsonApiModel_application-status_relationship"
        latestEvent:
          $ref: "../application/ApplicationEvent.yaml#/JsonApiModel_application-applicationEvent_relationship"
        thMatchType:
          $ref: "../application/thMatchType.yaml#/JsonApiModel_application-thMatchType_relationship"
  required:
    - schema
    - type
    - id
    - attributes
    - relationships

JsonApiModel_application_school:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - school
    type:
      $ref: "#/JsonApiModel_application_type"
    id:
      $ref: "#/JsonApiModel_application_id"
    attributes:
      type: object
      additionalProperties: false
      properties:
        # simple attributes
        creationDate:
          $ref: "../../library/application/application.yaml#/application_creationDate"
        submissionToSchoolDate:
          $ref: "../../library/application/application.yaml#/application_submissionToSchoolDate"
        latestUpdateDate:
          $ref: "../../library/application/application.yaml#/application_latestUpdateDate"
        recommendationText:
          $ref: "../../library/application/application.yaml#/application_recommendationText"
        # relationship attributes
        job:
          $ref: "../job/job.yaml#/JsonApiModel_job_relationship_attribute"
        teacher:
          $ref: "../teacher/teacher.yaml#/JsonApiModel_teacher_relationship_attribute"
        creationUser:
          $ref: "../user/user.yaml#/JsonApiModel_user_relationship_attribute"
        latestUpdateUser:
          $ref: "../user/user.yaml#/JsonApiModel_user_relationship_attribute"
        status:
          $ref: "../application/status.yaml#/JsonApiModel_application-status_relationship_attribute"
        latestEvent:
          $ref: "../application/ApplicationEvent.yaml#/JsonApiModel_application-applicationEvent_relationship_attribute"
        thMatchType:
          $ref: "../application/thMatchType.yaml#/JsonApiModel_application-thMatchType_relationship_attribute"
    relationships:
      type: object
      additionalProperties: false
      properties:
        job:
          $ref: "../job/job.yaml#/JsonApiModel_job_relationship"
        teacher:
          $ref: "../teacher/teacher.yaml#/JsonApiModel_teacher_relationship"
        creationUser:
          $ref: "../user/user.yaml#/JsonApiModel_user_relationship"
        latestUpdateUser:
          $ref: "../user/user.yaml#/JsonApiModel_user_relationship"
        status:
          $ref: "../application/status.yaml#/JsonApiModel_application-status_relationship"
        latestEvent:
          $ref: "../application/ApplicationEvent.yaml#/JsonApiModel_application-applicationEvent_relationship"
        thMatchType:
          $ref: "../application/thMatchType.yaml#/JsonApiModel_application-thMatchType_relationship"
  required:
    - schema
    - type
    - id
    - attributes
    - relationships

JsonApiModel_application_teacher:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - teacher
    type:
      $ref: "#/JsonApiModel_application_type"
    id:
      $ref: "#/JsonApiModel_application_id"
    attributes:
      type: object
      additionalProperties: false
      properties:
        # simple attributes
        creationDate:
          $ref: "../../library/application/application.yaml#/application_creationDate"
        submissionToSchoolDate:
          $ref: "../../library/application/application.yaml#/application_submissionToSchoolDate"
        latestUpdateDate:
          $ref: "../../library/application/application.yaml#/application_latestUpdateDate"
        # relationship attributes
        job:
          $ref: "../job/job.yaml#/JsonApiModel_job_relationship_attribute"
        teacher:
          $ref: "../teacher/teacher.yaml#/JsonApiModel_teacher_relationship_attribute"
        creationUser:
          $ref: "../user/user.yaml#/JsonApiModel_user_relationship_attribute"
        latestUpdateUser:
          $ref: "../user/user.yaml#/JsonApiModel_user_relationship_attribute"
        status:
          $ref: "../application/status.yaml#/JsonApiModel_application-status_relationship_attribute"
        latestEvent:
          $ref: "../application/ApplicationEvent.yaml#/JsonApiModel_application-applicationEvent_relationship_attribute"
    relationships:
      type: object
      additionalProperties: false
      properties:
        job:
          $ref: "../job/job.yaml#/JsonApiModel_job_relationship"
        teacher:
          $ref: "../teacher/teacher.yaml#/JsonApiModel_teacher_relationship"
        creationUser:
          $ref: "../user/user.yaml#/JsonApiModel_user_relationship"
        latestUpdateUser:
          $ref: "../user/user.yaml#/JsonApiModel_user_relationship"
        status:
          $ref: "../application/status.yaml#/JsonApiModel_application-status_relationship"
        latestEvent:
          $ref: "../application/ApplicationEvent.yaml#/JsonApiModel_application-applicationEvent_relationship"
  required:
    - schema
    - type
    - id
    - attributes
    - relationships

# type, id, relationship and relationship_attribute
JsonApiModel_application_type:
  type: string
  example: application
  description: Unique identifier of the entity type
  readOnly: true

JsonApiModel_application_id:
  type: string
  example: "1"
  readOnly: true
  description: Unique identifier of the entity (string)

JsonApiModel_application_relationship:
  type: object
  additionalProperties: false
  properties:
    data:
      type: object
      additionalProperties: false
      properties:
        type:
          $ref: "#/JsonApiModel_application_type"
        id:
          $ref: "#/JsonApiModel_application_id"
      required:
        - type
        - id
  required:
    - data

JsonApiModel_application_relationship_attribute:
  type: object
  additionalProperties: false
  properties:
    id:
      $ref: "#/JsonApiModel_application_id"
  required:
    - id
