JsonApiModel_application-applicationDataIssue:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '#/JsonApiModel_application-applicationDataIssue_type'
    id:
      $ref: '#/JsonApiModel_application-applicationDataIssue_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        # simple attributes
        date:
          $ref: '../../library/application/applicationDataIssue.yaml#/application-applicationDataIssue_date'
        name:
          $ref: '../../library/application/applicationDataIssue.yaml#/application-applicationDataIssue_name'
        # relationship attributes
        application:
          $ref: '../application/application.yaml#/JsonApiModel_application_relationship_attribute'
        guideline:
          $ref: '../application/guideline.yaml#/JsonApiModel_application-guideline_relationship_attribute'
    relationships:
      # $ref: "#/JsonApiModel_application-applicationDataIssue_relationships"
      type: object
      additionalProperties: false
      # description: Related Attributes
      properties:
        application:
          $ref: '../application/application.yaml#/JsonApiModel_application_relationship'
        guideline:
          $ref: '../application/guideline.yaml#/JsonApiModel_application-guideline_relationship'
  required:
    - type
    - id

JsonApiModel_application-applicationDataIssue_type:
  type: string
  example: application-applicationDataIssue
  description: Unique identifier of the entity type
  readOnly: true

JsonApiModel_application-applicationDataIssue_id:
  type: string
  example: '1'
  readOnly: true
  description: Unique identifier of the entity (string)

JsonApiModel_application-applicationDataIssue_relationship_attribute:
  type: object
  description: |
    Main properties of [application-applicationDataIssue](/#tag/simple-model-application-applicationDataIssue)
  additionalProperties: false
  properties:
    id:
      $ref: '#/JsonApiModel_application-applicationDataIssue_id'
    name:
      $ref: '../../library/application/applicationDataIssue.yaml#/application-applicationDataIssue_name'
  required:
    - id
    - name

JsonApiModel_application-applicationDataIssue_relationship:
  type: object
  description: |
    [Simple model](/#tag/simple-model-application-applicationDataIssue) | 
    [JSON:API model](/#tag/json-api-model-application-applicationDataIssue)
  additionalProperties: false
  properties:
    data:
      type: object
      additionalProperties: false
      properties:
        type:
          $ref: '#/JsonApiModel_application-applicationDataIssue_type'
        id:
          $ref: '#/JsonApiModel_application-applicationDataIssue_id'
      required:
        - type
        - id
  required:
    - data
