JsonApiModel_application:
  type: object
  properties:
    schema:
      $ref: "#/JsonApiModel_application_schema"
    type:
      $ref: "#/JsonApiModel_application_type"
    id:
      $ref: "#/JsonApiModel_application_id"
  discriminator:
    propertyName: schema
    mapping:
      all: "#/JsonApiModel_application_all"
      admin: "#/JsonApiModel_application_admin"
      teacher: "#/JsonApiModel_application_teacher"
  required:
    - schema
    - type
    - id

JsonApiModel_application_all:
  allOf:
    - $ref: "#/JsonApiModel_application"
    - properties:
        attributes:
          allOf:
            - $ref: "../../library/application/application.yaml#/application_attributes_all"
            - $ref: "../../library/application/application.yaml#/application_relationships_all"
        relationships:
          $ref: "#/JsonApiModel_application_relationships_all"

JsonApiModel_application_admin:
  allOf:
    - $ref: "#/JsonApiModel_application"
    - type: object
      properties:
        attributes:
          type: object
          allOf:
            - $ref: "../../library/application/application.yaml#/application_attributes_admin"
            # - $ref: "../../library/application/application.yaml#/application_relationships_admin"
        relationships:
          $ref: "#/JsonApiModel_application_relationships_admin"

JsonApiModel_application_teacher:
  allOf:
    - $ref: "#/JsonApiModel_application"
    - type: object
      properties:
        attributes:
          type: object
          allOf:
            - $ref: "../../library/application/application.yaml#/application_attributes_teacher"
            - $ref: "../../library/application/application.yaml#/application_relationships_teacher"
          # $ref: "#/JsonApiModel_application_attributes_teacher"
          # type: object
          # allOf:
          # - properties:
          #     creationDate:
          #       $ref: "../../library/application/application.yaml#/application_creationDate"
          #     latestUpdateDate:
          #       $ref: "../../library/application/application.yaml#/application_latestUpdateDate"
          # - $ref: "../../library/application/application.yaml#/application_properties_creationDate"
          # - $ref: "../../library/application/application.yaml#/application_attributes_teacher"
        # - $ref: "../../library/application/application.yaml#/application_relationships_teacher"
        relationships:
          $ref: "#/JsonApiModel_application_relationships_teacher"

JsonApiModel_application_attributes_teacher:
  allOf:
    # works
    # - $ref: "#/application_properties_creationDate2"
    # gives 'Recursive' error (even though essentially same as above - possibly because it's used elsewhere?)
    # edit: works when application_properties_creationDate is removed from elsewhere
    # edit: works when removed from only application_attributes_shared and application_attributes_teacher removed from C:\Dev\api\openapi\components\models\simple\application\application.yaml
    # edit: works when only SimpleModel_application is removed
    # - $ref: "../../library/application/application.yaml#/application_properties_creationDate"
    # works (once above works)
    - $ref: "../../library/application/application.yaml#/application_attributes_teacher"
    # works
    # - $ref: "../../library/application/application.yaml#/application_properties_creationDate3"
    # works
    # - properties:
    #     creationDate:
    #       $ref: "../../library/application/application.yaml#/application_creationDate"

application_properties_creationDate2:
  properties:
    creationDate:
      $ref: "#/application_creationDate2"

application_creationDate2:
  type: string
  format: date-time
  example: 2011-02-07T15:53:35Z

# relationships
JsonApiModel_application_relationships_all:
  allOf:
    - $ref: "#/JsonApiModel_application_relationships_admin"

JsonApiModel_application_relationships_admin:
  allOf:
    - $ref: "#/JsonApiModel_application_relationships_shared"
    - properties:
        thMatchType:
          $ref: "../application/thMatchType.yaml#/JsonApiModel_application-thMatchType_relationship"

JsonApiModel_application_relationships_teacher:
  allOf:
    - $ref: "#/JsonApiModel_application_relationships_shared"

JsonApiModel_application_relationships_shared:
  type: object
  properties:
    job:
      $ref: "../job/job.yaml#/JsonApiModel_job_relationship"
    teacher:
      $ref: "../teacher/teacher.yaml#/JsonApiModel_teacher_relationship"
    creationUser:
      $ref: "../user/user.yaml#/JsonApiModel_user_relationship"
    latestUpdateUser:
      $ref: "../user/user.yaml#/JsonApiModel_user_relationship"
    status:
      $ref: "../application/status.yaml#/JsonApiModel_application-status_relationship"
    latestEvent:
      $ref: "../application/ApplicationEvent.yaml#/JsonApiModel_application-applicationEvent_relationship"

# schema, type and id
JsonApiModel_application_schema:
  type: string
  example: admin
  enum:
    - admin
    - school
    - teacher

JsonApiModel_application_type:
  type: string
  example: application
  description: application
  readOnly: true

JsonApiModel_application_id:
  type: string
  example: "1"
  readOnly: true
  description: Unique identifier of the application (string)
