# yaml-language-server: $schema=../../../../../meta/schemas/JsonApiModel-MultipleSchemas.json

JsonApiModel_application-applicationEvent:
  oneOf:
    - $ref: '#/JsonApiModel_application-applicationEvent_admin'
    - $ref: '#/JsonApiModel_application-applicationEvent_school'
    - $ref: '#/JsonApiModel_application-applicationEvent_teacher'
  discriminator:
    propertyName: schema
    mapping:
      all: '#/JsonApiModel_application-applicationEvent_admin'
      admin: '#/JsonApiModel_application-applicationEvent_admin'
      school: '#/JsonApiModel_application-applicationEvent_school'
      teacher: '#/JsonApiModel_application-applicationEvent_teacher'

JsonApiModel_application-applicationEvent_admin:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - admin
    type:
      $ref: '#/JsonApiModel_application-applicationEvent_type'
    id:
      $ref: '#/JsonApiModel_application-applicationEvent_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        # simple attributes
        date:
          $ref: '../../library/application/applicationEvent.yaml#/application-applicationEvent_date'
        creationDate:
          $ref: '../../library/application/applicationEvent.yaml#/application-applicationEvent_creationDate'
        latestUpdateDate:
          $ref: '../../library/application/applicationEvent.yaml#/application-applicationEvent_latestUpdateDate'
        notes:
          $ref: '../../library/application/applicationEvent.yaml#/application-applicationEvent_notes'
        # relationship attributes
        type:
          $ref: './eventType.yaml#/JsonApiModel_application-eventType_relationship_attribute'
        creationUser:
          $ref: '../user/user.yaml#/JsonApiModel_user_relationship_attribute'
        latestUpdateUser:
          $ref: '../user/user.yaml#/JsonApiModel_user_relationship_attribute'
    relationships:
      type: object
      additionalProperties: false
      properties:
        type:
          $ref: './eventType.yaml#/JsonApiModel_application-eventType_relationship'
        creationUser:
          $ref: '../user/user.yaml#/JsonApiModel_user_relationship'
        latestUpdateUser:
          $ref: '../user/user.yaml#/JsonApiModel_user_relationship'
  required:
    - schema
    - type
    - id
    - attributes
    - relationships

JsonApiModel_application-applicationEvent_school:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - school
    type:
      $ref: '#/JsonApiModel_application-applicationEvent_type'
    id:
      $ref: '#/JsonApiModel_application-applicationEvent_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        # simple attributes
        date:
          $ref: '../../library/application/applicationEvent.yaml#/application-applicationEvent_date'
        latestUpdateDate:
          $ref: '../../library/application/applicationEvent.yaml#/application-applicationEvent_latestUpdateDate'
  required:
    - schema
    - type
    - id
    - attributes

JsonApiModel_application-applicationEvent_teacher:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - teacher
    type:
      $ref: '#/JsonApiModel_application-applicationEvent_type'
    id:
      $ref: '#/JsonApiModel_application-applicationEvent_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        # simple attributes
        date:
          $ref: '../../library/application/applicationEvent.yaml#/application-applicationEvent_date'
        latestUpdateDate:
          $ref: '../../library/application/applicationEvent.yaml#/application-applicationEvent_latestUpdateDate'
  required:
    - schema
    - type
    - id
    - attributes

# type, id, attribute and relationship
JsonApiModel_application-applicationEvent_type:
  type: string
  example: application-applicationEvent
  description: Unique identifier of the entity type
  readOnly: true

JsonApiModel_application-applicationEvent_id:
  type: string
  example: '1'
  description: Unique identifier of the entity (string)
  readOnly: true

JsonApiModel_application-applicationEvent_relationship_attribute:
  type: object
  additionalProperties: false
  properties:
    id:
      $ref: '#/JsonApiModel_application-applicationEvent_id'
    notes:
      $ref: '../../library/application/applicationEvent.yaml#/application-applicationEvent_notes'
  required:
    - id
    - notes

JsonApiModel_application-applicationEvent_relationship:
  type: object
  additionalProperties: false
  properties:
    data:
      type: object
      additionalProperties: false
      properties:
        type:
          $ref: '#/JsonApiModel_application-applicationEvent_type'
        id:
          $ref: '#/JsonApiModel_application-applicationEvent_id'
      required:
        - type
        - id
  required:
    - data
