JsonApiModel_application:
  type: object
  properties:
    schema:
      $ref: "#/JsonApiModel_application_schema"
    type:
      $ref: "#/JsonApiModel_application_type"
    id:
      $ref: "#/JsonApiModel_application_id"
  discriminator:
    propertyName: schema
    mapping:
      all: "#/JsonApiModel_application_all"
      admin: "#/JsonApiModel_application_admin"
      teacher: "#/JsonApiModel_application_teacher"
  required:
    - schema
    - type
    - id

JsonApiModel_application_all:
  allOf:
    - $ref: "#/JsonApiModel_application"
    - properties:
        attributes:
          $ref: "#/JsonApiModel_application_attributes_all"
        relationships:
          $ref: "#/JsonApiModel_application_relationships_all"

JsonApiModel_application_admin:
  allOf:
    - $ref: "#/JsonApiModel_application"
    - properties:
        attributes:
          $ref: "#/JsonApiModel_application_attributes_admin"
        relationships:
          $ref: "#/JsonApiModel_application_relationships_admin"

JsonApiModel_application_teacher:
  allOf:
    - $ref: "#/JsonApiModel_application"
    - properties:
        attributes:
          $ref: "#/JsonApiModel_application_attributes_teacher"
        relationships:
          $ref: "#/JsonApiModel_application_relationships_teacher"

# schema, type and id
JsonApiModel_application_schema:
  type: string
  example: admin
  enum:
    - admin
    - school
    - teacher

JsonApiModel_application_type:
  type: string
  example: application
  description: application
  readOnly: true

JsonApiModel_application_id:
  type: string
  example: "1"
  readOnly: true
  description: Unique identifier of the application (string)

JsonApiModel_application_relationship:
  type: object
  properties:
    data:
      type: object
      properties:
        type:
          $ref: "#/JsonApiModel_application_type"
        id:
          $ref: "#/JsonApiModel_application_id"

# attributes
JsonApiModel_application_attributes_all:
  allOf:
    - $ref: "#/JsonApiModel_application_attributes_admin"

JsonApiModel_application_attributes_admin:
  allOf:
    - $ref: "#/JsonApiModel_application_attributes_shared"
    - properties:
        # simple attributes
        recommendationText:
          $ref: "../../library/application/application.yaml#/application_recommendationText"
        thSystemMatchScore:
          $ref: "../../library/application/application.yaml#/application_thSystemMatchScore"
        hasDataIssues:
          $ref: "../../library/application/application.yaml#/application_hasDataIssues"
        # relationship attributes
        thMatchTypeId:
          $ref: "../../library/application/application.yaml#/application_thMatchTypeId"

JsonApiModel_application_attributes_teacher:
  allOf:
    - $ref: "#/JsonApiModel_application_attributes_shared"

JsonApiModel_application_attributes_shared:
  properties:
    # simple attributes
    creationDate:
      $ref: "../../library/application/application.yaml#/application_creationDate"
    latestUpdateDate:
      $ref: "../../library/application/application.yaml#/application_latestUpdateDate"
    # relationship attributes
    jobId:
      $ref: "../../library/application/application.yaml#/application_jobId"
    teacherId:
      $ref: "../../library/application/application.yaml#/application_teacherId"
    creationUserId:
      $ref: "../../library/application/application.yaml#/application_creationUserId"
    latestUpdateUserId:
      $ref: "../../library/application/application.yaml#/application_latestUpdateUserId"
    statusId:
      $ref: "../../library/application/application.yaml#/application_statusId"
    latestEventId:
      $ref: "../../library/application/application.yaml#/application_latestEventId"

# relationships
JsonApiModel_application_relationships_all:
  allOf:
    - $ref: "#/JsonApiModel_application_relationships_admin"

JsonApiModel_application_relationships_admin:
  allOf:
    - $ref: "#/JsonApiModel_application_relationships_shared"
    - properties:
        thMatchType:
          $ref: "../application/thMatchType.yaml#/JsonApiModel_application-thMatchType_relationship"

JsonApiModel_application_relationships_teacher:
  allOf:
    - $ref: "#/JsonApiModel_application_relationships_shared"

JsonApiModel_application_relationships_shared:
  type: object
  properties:
    job:
      $ref: "../job/job.yaml#/JsonApiModel_job_relationship"
    teacher:
      $ref: "../teacher/teacher.yaml#/JsonApiModel_teacher_relationship"
    creationUser:
      $ref: "../user/user.yaml#/JsonApiModel_user_relationship"
    latestUpdateUser:
      $ref: "../user/user.yaml#/JsonApiModel_user_relationship"
    status:
      $ref: "../application/status.yaml#/JsonApiModel_application-status_relationship"
    # latestEvent:
    #   $ref: "../application/ApplicationEvent.yaml#/JsonApiModel_application-applicationEvent_relationship"
