# yaml-language-server: $schema=../../../../../meta/JsonApiModel-MultipleSchemas.json

JsonApiModel_application-applicationEvent:
  oneOf:
    - $ref: "#/JsonApiModel_application-applicationEvent_admin"
    - $ref: "#/JsonApiModel_application-applicationEvent_school"
    - $ref: "#/JsonApiModel_application-applicationEvent_teacher"
  discriminator:
    propertyName: schema
    mapping:
      all: "#/JsonApiModel_application-applicationEvent_admin"
      admin: "#/JsonApiModel_application-applicationEvent_admin"
      school: "#/JsonApiModel_application-applicationEvent_school"
      teacher: "#/JsonApiModel_application-applicationEvent_teacher"

JsonApiModel_application-applicationEvent_admin:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - admin
    type:
      $ref: "#/JsonApiModel_application-applicationEvent_type"
    id:
      $ref: "#/JsonApiModel_application-applicationEvent_id"
    attributes:
      type: object
      additionalProperties: false
      properties:
        # simple attributes
        date:
          $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_date"
        creationDate:
          $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_creationDate"
        latestUpdateDate:
          $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_latestUpdateDate"
        notes:
          $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_notes"
        # relationship attributes
        type:
          $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_type"
        creationUser:
          $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_creationUser"
        latestUpdateUser:
          $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_latestUpdateUser"
    relationships:
      type: object
      additionalProperties: false
      properties:
        type:
          $ref: "./eventType.yaml#/JsonApiModel_application-eventType_relationship"
        creationUser:
          $ref: "../../json-api/user/user.yaml#/JsonApiModel_user_relationship"
        latestUpdateUser:
          $ref: "../../json-api/user/user.yaml#/JsonApiModel_user_relationship"
      required:
        - creationUser
        - latestUpdateUser

JsonApiModel_application-applicationEvent_school:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - school
    # simple attributes
    date:
      $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_date"
    latestUpdateDate:
      $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_latestUpdateDate"

JsonApiModel_application-applicationEvent_teacher:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - teacher
    # simple attributes
    date:
      $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_date"
    latestUpdateDate:
      $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_latestUpdateDate"

# JsonApiModel_application-applicationEvent_schema:
#   type: string
#   example: admin
#   enum:
#     - admin
#     - school
#     - teacher

# type and id
JsonApiModel_application-applicationEvent_type:
  type: string
  example: application-applicationEvent
  description: application-applicationEvent
  readOnly: true

JsonApiModel_application-applicationEvent_id:
  type: string
  example: "1"
  description: Unique identifier of the application-applicationEvent (string)
  readOnly: true

JsonApiModel_application-applicationEvent_relationship_attribute:
  type: object
  properties:
    id:
      $ref: "#/JsonApiModel_application-applicationEvent_id"

JsonApiModel_application-applicationEvent_relationship:
  type: object
  properties:
    data:
      type: object
      properties:
        type:
          $ref: "#/JsonApiModel_application-applicationEvent_type"
        id:
          $ref: "#/JsonApiModel_application-applicationEvent_id"
