JsonApiModel_applicationAction:
  type: object
  properties:
    schema:
      type: string
      example: admin
  discriminator:
    propertyName: schema
    mapping:
      admin: "#/JsonApiModel_applicationAction_admin"

JsonApiModel_applicationAction_admin:
  allOf:
    - $ref: "#/JsonApiModel_applicationAction"
    - type: object
    - properties:
        $ref: "#/JsonApiModel_applicationAction_attributes_admin"
    - required:
        - type
        - id

# admin
JsonApiModel_applicationAction_attributes_admin:
  type:
    $ref: "#/JsonApiModel_applicationAction_type"
  id:
    $ref: "#/JsonApiModel_applicationAction_id"
  attributes:
    allOf:
      - $ref: "../../library/applications/ApplicationAction.yaml#/ApplicationAction_standardProperties_adminOnly"
  relationships:
    $ref: "#/JsonApiModel_applicationAction_relationships_admin"

# JsonApiModel_applicationAction_relationships_admin:
#   type: object
#   description: Related attributes
#   properties:
#     $ref: "../../library/applications/ApplicationAction.yaml#/ApplicationAction_relationshipProperties_adminOnly2"

JsonApiModel_applicationAction_relationships_admin:
  type: object
  description: Related attributes
  $ref: "../../library/applications/ApplicationAction.yaml#/ApplicationAction_relationshipProperties_adminOnly"

# shared
JsonApiModel_applicationAction_type:
  type: string
  example: applicationAction
  description: applicationAction
  readOnly: true

JsonApiModel_applicationAction_id:
  type: string
  example: "1"
  readOnly: true
  description: Unique identifier of the applicationAction (string)
