JsonApiModel_application-applicationEvent:
  type: object
  properties:
    type:
      $ref: "#/JsonApiModel_application-applicationEvent_type"
    id:
      $ref: "#/JsonApiModel_application-applicationEvent_id"
    attributes:
      allOf:
        - $ref: "../../library/application/applicationEvent.yaml#/application-applicationEvent_attributes_admin"
    relationships:
      $ref: "#/JsonApiModel_application-applicationEvent_relationships"
      attributes:
        allOf:
          $ref: "../../library/application/applicationEvent.yaml#/application-ApplicationEvent_relationships"
  required:
    - type
    - id

JsonApiModel_application-applicationEvent_relationships:
  type: object
  description: Related Attributes
  properties:
    application:
      $ref: "../../../schemas/proposed/simple-models/helpers/json-api.yaml#/RelToOne"
    type:
      $ref: "../../../schemas/proposed/simple-models/helpers/json-api.yaml#/RelToOne"
    email:
      $ref: "../../../schemas/proposed/simple-models/helpers/json-api.yaml#/RelToOne"
    creationUser:
      $ref: "../../../schemas/proposed/simple-models/helpers/json-api.yaml#/RelToOne"
    latestUpdateUser:
      $ref: "../../../schemas/proposed/simple-models/helpers/json-api.yaml#/RelToOne"

JsonApiModel_application-applicationEvent_type:
  type: string
  example: application-applicationEvent
  description: application-applicationEvent
  readOnly: true

JsonApiModel_application-applicationEvent_id:
  type: string
  example: "1"
  readOnly: true
  description: Unique identifier of the application-applicationEvent (string)

JsonApiModel_application-applicationEvent_relationship:
  type: object
  properties:
    data:
      type: object
      properties:
        type:
          $ref: "#/JsonApiModel_application-applicationEvent_type"
        id:
          $ref: "#/JsonApiModel_application-applicationEvent_id"
