JsonApiModel_application:
  oneOf:
    - $ref: "#/JsonApiModel_application_admin"
    - $ref: "#/JsonApiModel_application_school"
    - $ref: "#/JsonApiModel_application_teacher"
  discriminator:
    propertyName: schema
    mapping:
      all: "#/JsonApiModel_application_admin"
      admin: "#/JsonApiModel_application_admin"
      school: "#/JsonApiModel_application_school"
      teacher: "#/JsonApiModel_application_teacher"

JsonApiModel_application_admin:
  type: object
  additionalProperties: false
  properties:
    schema:
      $ref: "#/JsonApiModel_application_schema"
    type:
      $ref: "#/JsonApiModel_application_type"
    id:
      $ref: "#/JsonApiModel_application_id"  
    attributes:
      $ref: "#/JsonApiModel_application_attributes_admin"
    relationships:
      $ref: "#/JsonApiModel_application_relationships_admin"
  required:
    - schema
    - type
    - id
    - attributes
    - relationships

JsonApiModel_application_school:
  type: object
  additionalProperties: false
  properties:
    schema:
      $ref: "#/JsonApiModel_application_schema"
    type:
      $ref: "#/JsonApiModel_application_type"
    id:
      $ref: "#/JsonApiModel_application_id"  
    attributes:
      $ref: "#/JsonApiModel_application_attributes_school"
    relationships:
      $ref: "#/JsonApiModel_application_relationships_school"
  required:
    - schema
    - type
    - id
    - attributes
    - relationships

JsonApiModel_application_teacher:
  type: object
  additionalProperties: false
  properties:
    schema:
      $ref: "#/JsonApiModel_application_schema"
    type:
      $ref: "#/JsonApiModel_application_type"
    id:
      $ref: "#/JsonApiModel_application_id"  
    attributes:
      $ref: "#/JsonApiModel_application_attributes_teacher"
    relationships:
      $ref: "#/JsonApiModel_application_relationships_teacher"
  required:
    - schema
    - type
    - id
    - attributes
    - relationships

# schema, type and id
JsonApiModel_application_schema:
  type: string
  example: admin
  enum:
    - admin
    - school
    - teacher

JsonApiModel_application_type:
  type: string
  example: application
  description: application
  readOnly: true

JsonApiModel_application_id:
  type: string
  example: "1"
  readOnly: true
  description: Unique identifier of the application (string)

JsonApiModel_application_relationship:
  type: object
  properties:
    data:
      type: object
      properties:
        type:
          $ref: "#/JsonApiModel_application_type"
        id:
          $ref: "#/JsonApiModel_application_id"
      required:
        - type
        - id
  required:
    - data

# attributes
JsonApiModel_application_attributes_all:
  allOf:
    - $ref: "#/JsonApiModel_application_attributes_admin"

JsonApiModel_application_attributes_admin:
  allOf:
    - $ref: "#/JsonApiModel_application_attributes_shared"
    - properties:
        # simple attributes
        recommendationText:
          $ref: "../../library/application/application.yaml#/application_recommendationText"
        thSystemMatchScore:
          $ref: "../../library/application/application.yaml#/application_thSystemMatchScore"
        hasDataIssues:
          $ref: "../../library/application/application.yaml#/application_hasDataIssues"
        # relationship attributes
        thMatchType:
          $ref: "../../library/application/application.yaml#/application_thMatchTypeId"

JsonApiModel_application_attributes_school:
  allOf:
    - $ref: "#/JsonApiModel_application_attributes_shared"
    - properties:
        # simple attributes
        recommendationText:
          $ref: "../../library/application/application.yaml#/application_recommendationText"
        # relationship attributes
        thMatchType:
          $ref: "../../library/application/application.yaml#/application_thMatchTypeId"

JsonApiModel_application_attributes_teacher:
  allOf:
    - $ref: "#/JsonApiModel_application_attributes_shared"

JsonApiModel_application_attributes_shared:
  properties:
    # simple attributes
    creationDate:
      $ref: "../../library/application/application.yaml#/application_creationDate"
    submissionToSchoolDate:
      $ref: "../../library/application/application.yaml#/application_submissionToSchoolDate"
    latestUpdateDate:
      $ref: "../../library/application/application.yaml#/application_latestUpdateDate"
    # relationship attributes
    job:
      $ref: "../job/job.yaml#/JsonApiModel_job_relationship_attribute"
    teacher:
      $ref: "../teacher/teacher.yaml#/JsonApiModel_teacher_relationship_attribute"
    creationUser:
      $ref: "../user/user.yaml#/JsonApiModel_user_relationship_attribute"
    latestUpdateUser:
      $ref: "../user/user.yaml#/JsonApiModel_user_relationship_attribute"
    status:
      $ref: "../application/status.yaml#/JsonApiModel_application-status_relationship_attribute"
    latestEvent:
      $ref: "../application/ApplicationEvent.yaml#/JsonApiModel_application-applicationEvent_relationship_attribute"

# relationships
JsonApiModel_application_relationships_all:
  allOf:
    - $ref: "#/JsonApiModel_application_relationships_admin"

JsonApiModel_application_relationships_admin:
  allOf:
    - $ref: "#/JsonApiModel_application_relationships_shared"
    - properties:
        thMatchType:
          $ref: "../application/thMatchType.yaml#/JsonApiModel_application-thMatchType_relationship"

JsonApiModel_application_relationships_school:
  allOf:
    - $ref: "#/JsonApiModel_application_relationships_shared"
    - properties:
        thMatchType:
          $ref: "../application/thMatchType.yaml#/JsonApiModel_application-thMatchType_relationship"

JsonApiModel_application_relationships_teacher:
  allOf:
    - $ref: "#/JsonApiModel_application_relationships_shared"

JsonApiModel_application_relationships_shared:
  type: object
  properties:
    job:
      $ref: "../job/job.yaml#/JsonApiModel_job_relationship"
    teacher:
      $ref: "../teacher/teacher.yaml#/JsonApiModel_teacher_relationship"
    creationUser:
      $ref: "../user/user.yaml#/JsonApiModel_user_relationship"
    latestUpdateUser:
      $ref: "../user/user.yaml#/JsonApiModel_user_relationship"
    status:
      $ref: "../application/status.yaml#/JsonApiModel_application-status_relationship"
    # latestEvent:
    #   $ref: "../application/ApplicationEvent.yaml#/JsonApiModel_application-applicationEvent_relationship"

JsonApiModel_application_relationship_attribute:
  type: object
  properties:
    id:
      $ref: "#/JsonApiModel_application_id"
