JsonApiModel_application:
  type: object
  properties:
    type:
      $ref: "#/JsonApiModel_application_type"
    id:
      $ref: "#/JsonApiModel_application_id"
    attributes:
      allOf:
        - $ref: "../../library/application/application.yaml#/application_attributes"
    relationships:
      $ref: "#/JsonApiModel_application_relationships"
      attributes:
        allOf:
          $ref: "../../library/application/application.yaml#/application_relationships"
  required:
    - type
    - id

JsonApiModel_application_relationships:
  type: object
  description: Related attributes
  properties:
    applicationType:
      $ref: "../../../schemas/proposed/simple-models/helpers/json-api.yaml#/RelToOne"
    creationUser:
      $ref: "../../../schemas/proposed/simple-models/helpers/json-api.yaml#/RelToOne"
    latestUpdateUser:
      $ref: "../../../schemas/proposed/simple-models/helpers/json-api.yaml#/RelToOne"

JsonApiModel_application_type:
  type: string
  example: application
  description: application
  readOnly: true

JsonApiModel_application_id:
  type: string
  example: "1"
  readOnly: true
  description: Unique identifier of the application (string)
