Response_application-applicationDataIssues:
  oneOf:
    - $ref: '#/Response_application-applicationDataIssues_admin'
    - $ref: '#/Response_application-applicationDataIssues_admin-v2'
  discriminator:
    propertyName: schema
    mapping:
      admin: '#/Response_application-applicationDataIssues_admin'
      admin-v2: '#/Response_application-applicationDataIssues_admin-v2'

# admin (non-standard, deprecated)
Response_application-applicationDataIssues_admin:
  type: object
  additionalProperties: false
  properties:
    # property isn't returned by API call, but this is need here for openapi to work
    schema:
      deprecated: true
      type: string
      enum:
        - admin
    data:
      type: array
      description: |
        [Simple model](/#tag/simple-model-application-applicationDataIssues) | 
        [JSON:API model](/#tag/json-api-model-application-applicationDataIssues)
      items:
        $ref: '#/Response_application-applicationDataIssues_admin_item'
  required:
    # note: actual api response doesn't have a schema
    # - schema
    - data

Response_application-applicationDataIssues_admin_item:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '../../../components/models/json-api/application/applicationDataIssue.yaml#/JsonApiModel_application-applicationDataIssue_type'
    id:
      $ref: '../../../components/models/json-api/application/applicationDataIssue.yaml#/JsonApiModel_application-applicationDataIssue_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        # Name of the related guideline (non-standard json-api)
        name:
          $ref: '../../../components/models/library/application/guideline.yaml#/application-guideline_name'
      required:
        - name
  required:
    - type
    - id
    - attributes

# admin-v2
Response_application-applicationDataIssues_admin-v2:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - admin-v2
    data:
      type: array
      description: |
        [Simple model](/#tag/simple-model-application-applicationDataIssue) | 
        [JSON:API model](/#tag/json-api-model-application-applicationDataIssue)
      items:
        $ref: '#/Response_application-applicationDataIssues_admin-v2_item'
    # included:
    #   type: array
    #   items:
    #     anyOf:
    #       - $ref: '#/Response_application-applicationDataIssues_includedGuideline_admin-v2'
  required:
    # - schema
    - data
    # - included

Response_application-applicationDataIssues_admin-v2_item:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '../../../components/models/json-api/application/applicationDataIssue.yaml#/JsonApiModel_application-applicationDataIssue_type'
    id:
      $ref: '../../../components/models/json-api/application/applicationDataIssue.yaml#/JsonApiModel_application-applicationDataIssue_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        #simple attribute
        date:
          $ref: '../../../components/models/library/application/applicationDataIssue.yaml#/application-applicationDataIssue_date'
        #relationship attribute
        guideline:
          $ref: '../../../components/models/json-api/application/guideline.yaml#/JsonApiModel_application-guideline_relationship_attribute'
      required:
        - date
        - guideline
  required:
    - type
    - id
    - attributes

Response_application-applicationDataIssues_includedGuideline_admin-v2:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '../../../components/models/json-api/application/applicationDataIssue.yaml#/JsonApiModel_application-applicationDataIssue_type'
    id:
      $ref: '../../../components/models/json-api/application/applicationDataIssue.yaml#/JsonApiModel_application-applicationDataIssue_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        name:
          $ref: '../../../components/models/library/application/guideline.yaml#/application-guideline_name'
      required:
        - name
  required:
    - type
    - id
    - attributes
