Application-applicationEventsResponse:
  oneOf:
    - $ref: "#/Application-applicationEventsResponse_admin-oneApplication"
    - $ref: "#/Application-applicationEventsResponse_admin-allApplications"
    - $ref: "#/Application-applicationEventsResponse_school"
    - $ref: "#/Application-applicationEventsResponse_teacher"
  discriminator:
    propertyName: schema
    mapping:
      admin-oneApplication: "#/Application-applicationEventsResponse_admin-oneApplication"
      admin-allApplications: "#/Application-applicationEventsResponse_admin-allApplications"
      school: "#/Application-applicationEventsResponse_school"
      teacher: "#/Application-applicationEventsResponse_teacher"

# admin-oneApplication
Application-applicationEventsResponse_admin-oneApplication:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - admin-oneApplication
    data:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          type:
            $ref: "../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_type"
          id:
            $ref: "../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_id"
          attributes:
            type: object
            additionalProperties: false
            properties:
              type:
                $ref: "../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_type"
              date:
                $ref: "../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_date"
              creationDate:
                $ref: "../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_creationDate"
              latestUpdateDate:
                $ref: "../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_latestUpdateDate"
              notes:
                $ref: "../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_notes"
            required:
              - type
              - date
              - creationDate
              - latestUpdateDate
          relationships:
            type: object
            additionalProperties: false
            properties:
              creationUser:
                $ref: "../../../components/models/json-api/user/user.yaml#/JsonApiModel_user_relationship"
              latestUpdateUser:
                $ref: "../../../components/models/json-api/user/user.yaml#/JsonApiModel_user_relationship"
            required:
              - creationUser
              - latestUpdateUser
        required:
          - type
          - id
          - attributes
          - relationships
    included:
      type: array
      items:
        $ref: "#/Application-applicationEventsResponse_includedUser_admin-oneApplication"
  required:
    - schema
    - data
    - included

Application-applicationEventsResponse_includedUser_admin-oneApplication:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: "../../../components/models/json-api/user/user.yaml#/JsonApiModel_user_type"
    id:
      $ref: "../../../components/models/json-api/user/user.yaml#/JsonApiModel_user_id"
    attributes:
      type: object
      additionalProperties: false
      properties:
        firstName:
          $ref: "../../../components/models/library/user/user.yaml#/user_firstName"
        lastName:
          $ref: "../../../components/models/library/user/user.yaml#/user_lastName"
      required:
        - firstName
        - lastName
  required:
    - type
    - id
    - attributes

# admin-allApplications
Application-applicationEventsResponse_admin-allApplications:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - admin-allApplications
    data:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          type:
            $ref: "../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_type"
          id:
            $ref: "../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_id"
          attributes:
            type: object
            additionalProperties: false
            properties:
              type:
                $ref: "../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_type"
              date:
                $ref: "../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_date"
              creationDate:
                $ref: "../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_creationDate"
              latestUpdateDate:
                $ref: "../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_latestUpdateDate"
              notes:
                $ref: "../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_notes"
            required:
              - type
              - date
              - creationDate
              - latestUpdateDate
          relationships:
            type: object
            additionalProperties: false
            properties:
              application:
                $ref: "../../../components/models/json-api/application/application.yaml#/JsonApiModel_application_relationship"
              creationUser:
                $ref: "../../../components/models/json-api/user/user.yaml#/JsonApiModel_user_relationship"
              latestUpdateUser:
                $ref: "../../../components/models/json-api/user/user.yaml#/JsonApiModel_user_relationship"
            required:
              - application
              - creationUser
              - latestUpdateUser
        required:
          - type
          - id
          - attributes
          - relationships
    included:
      type: array
      items:
        anyOf:
          - $ref: "#/Application-applicationEventsResponse_includedUser_admin-allApplications"
          - $ref: "#/Application-applicationEventsResponse_includedApplication_admin-allApplications"
          - $ref: "#/Application-applicationEventsResponse_includedJob_admin-allApplications"
          - $ref: "#/Application-applicationEventsResponse_includedSchool_admin-allApplications"
  required:
    - schema
    - data
    - included

Application-applicationEventsResponse_includedUser_admin-allApplications:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: "../../../components/models/json-api/user/user.yaml#/JsonApiModel_user_type"
    id:
      $ref: "../../../components/models/json-api/user/user.yaml#/JsonApiModel_user_id"
    attributes:
      type: object
      additionalProperties: false
      properties:
        firstName:
          $ref: "../../../components/models/library/user/user.yaml#/user_firstName"
        lastName:
          $ref: "../../../components/models/library/user/user.yaml#/user_lastName"
      required:
        - firstName
        - lastName
  required:
    - type
    - id
    - attributes

Application-applicationEventsResponse_includedApplication_admin-allApplications:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: "../../../components/models/json-api/application/application.yaml#/JsonApiModel_application_type"
    id:
      $ref: "../../../components/models/json-api/application/application.yaml#/JsonApiModel_application_id"
    attributes:
      type: object
      additionalProperties: false
      properties:
        status:
          $ref: "../../../components/models/library/application/application.yaml#/application_status"
      required:
        - status
    relationships:
      type: object
      additionalProperties: false
      properties:
        job:
          $ref: "../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_relationship"
      required:
        - job
  required:
    - type
    - id
    - attributes
    - relationships

Application-applicationEventsResponse_includedJob_admin-allApplications:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: "../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_type"
    id:
      $ref: "../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_id"
    attributes:
      type: object
      additionalProperties: false
      properties:
        title:
          $ref: "../../../components/models/library/job/job.yaml#/job_title"
      required:
        - title
    relationships:
      type: object
      additionalProperties: false
      properties:
        school:
          $ref: "../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_relationship"
      required:
        - school
  required:
    - type
    - id
    - attributes
    - relationships

Application-applicationEventsResponse_includedSchool_admin-allApplications:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: "../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_type"
    id:
      $ref: "../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_id"
    attributes:
      type: object
      additionalProperties: false
      properties:
        name:
          $ref: "../../../components/models/library/school/school.yaml#/school_name"
        slug:
          $ref: "../../../components/models/library/school/school.yaml#/school_slug"
      required:
        - name
        - slug
  required:
    - type
    - id
    - attributes

# teacher
Application-applicationEventsResponse_teacher:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - teacher
    data:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          type:
            $ref: "../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_type"
          id:
            $ref: "../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_id"
          attributes:
            type: object
            additionalProperties: false
            properties:
              type:
                $ref: "../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_type"
              date:
                $ref: "../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_date"
            required:
              - type
              - date
        required:
          - type
          - id
          - attributes
  required:
    - schema
    - data

# school
Application-applicationEventsResponse_school:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - school
    data:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          type:
            $ref: "../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_type"
          id:
            $ref: "../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_id"
          attributes:
            type: object
            additionalProperties: false
            properties:
              type:
                $ref: "../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_type"
              date:
                $ref: "../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_date"
            required:
              - type
              - date
        required:
          - type
          - id
          - attributes
  required:
    - schema
    - data
