Response_applications:
  oneOf:
    - $ref: '#/Response_applications_admin'
    - $ref: '#/Response_applications_school'
    - $ref: '#/Response_applications_teacher'
  discriminator:
    propertyName: schema
    mapping:
      admin: '#/Response_applications_admin'
      school: '#/Response_applications_school'
      teacher: '#/Response_applications_teacher'

Response_applications_meta:
  type: object
  properties:
    count:
      type: integer
      example: 123
    pageCount:
      type: integer
      example: 20
  required:
    - count
    - pageCount

# admin
Response_applications_admin:
  type: object
  # description: |
  #   [Simple model](/#tag/simple-model-applications) | 
  #   [JSON:API model](/#tag/json-api-model-applications)
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - admin
    meta:
      $ref: '#/Response_applications_meta'
    data:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          type:
            $ref: '../../../components/models/json-api/application/application.yaml#/JsonApiModel_application_type'
          id:
            $ref: '../../../components/models/json-api/application/application.yaml#/JsonApiModel_application_id'
          attributes:
            type: object
            additionalProperties: false
            properties:
              # simple attributes
              # creationDate: # not used => remove
              #   $ref: "../../../components/models/library/application/application.yaml#/application_creationDate"
              latestUpdateDate:
                $ref: '../../../components/models/library/application/application.yaml#/application_latestUpdateDate'
              # relationship attributes
              thMatchType:
                $ref: '../../../components/models/json-api/application/thMatchType.yaml#/JsonApiModel_application-thMatchType_relationship_attribute'
              status:
                $ref: '../../../components/models/json-api/application/status.yaml#/JsonApiModel_application-status_relationship_attribute'
                # allOf:
                # - $ref: "../../../components/models/library/application/application.yaml#/application_attributes_admin"
                # - $ref: "../../../components/models/library/application/application.yaml#/application_properties_status"
            required:
              - latestUpdateDate
              - status
          relationships:
            type: object
            additionalProperties: false
            properties:
              job:
                $ref: '../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_relationship'
              teacher:
                $ref: '../../../components/models/json-api/teacher/teacher.yaml#/JsonApiModel_teacher_relationship'
              latestEvent:
                $ref: '../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_relationship'
        required:
          - type
          - id
          - attributes
          - relationships
    included:
      type: array
      items:
        anyOf:
          - $ref: '#/Response_applications_includedTeacher_admin'
          - $ref: '#/Response_applications_includedJob_admin'
          - $ref: '#/Response_applications_includedSchool_admin'
          - $ref: '#/Response_applications_includedApplicationEvent_admin'
  required:
    - schema
    - data

Response_applications_includedTeacher_admin:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '../../../components/models/json-api/teacher/teacher.yaml#/JsonApiModel_teacher_type'
    id:
      $ref: '../../../components/models/json-api/teacher/teacher.yaml#/JsonApiModel_teacher_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        memberNumber:
          $ref: '../../../components/models/library/teacher/teacher.yaml#/teacher_memberNumber'
        thDoNotContact:
          $ref: '../../../components/models/library/teacher/teacher.yaml#/teacher_thDoNotContact'
        thPlaceabilityRating:
          $ref: '../../../components/models/library/teacher/teacher.yaml#/teacher_thPlaceabilityRating'
        fullName:
          $ref: '../../../components/models/library/teacher/teacher.yaml#/teacher_fullName'
        profilePhotoUrl:
          $ref: '../../../components/models/library/teacher/teacher.yaml#/teacher_profilePhotoUrl'
      required:
        - memberNumber
        - thDoNotContact
        - fullName
        - profilePhotoUrl
  required:
    - type
    - id
    - attributes

Response_applications_includedJob_admin:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_type'
    id:
      $ref: '../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        title:
          $ref: '../../../components/models/library/job/job.yaml#/job_title'
      required:
        - title
    relationships:
      type: object
      additionalProperties: false
      properties:
        school:
          $ref: '../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_relationship'
      required:
        - school
  required:
    - type
    - id
    - attributes
    - relationships

Response_applications_includedSchool_admin:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_type'
    id:
      $ref: '../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        # simple attributes
        name:
          $ref: '../../../components/models/library/school/school.yaml#/school_name'
        slug:
          $ref: '../../../components/models/library/school/school.yaml#/school_slug'
        thRating:
          $ref: '../../../components/models/library/school/school.yaml#/school_thRating'
        # relationship attributes
        city:
          $ref: '../../../components/models/json-api/regional/city.yaml#/JsonApiModel_regional-city_relationship_attribute'
      required:
        - name
        - slug
        - thRating
        - city
  required:
    - type
    - id
    - attributes

Response_applications_includedApplicationEvent_admin:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_type'
    id:
      $ref: '../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        # simple attributes
        date:
          $ref: '../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_date'
        # relationship attributes
        type:
          $ref: '../../../components/models/json-api/application/eventType.yaml#/JsonApiModel_application-eventType_relationship_attribute'
      required:
        - date
        - type
  required:
    - type
    - id
    - attributes

# teacher
Response_applications_teacher:
  type: object
  additionalProperties: false
  properties:
    meta:
      $ref: '#/Response_applications_meta'
    schema:
      type: string
      enum:
        - admin
    data:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          type:
            $ref: '../../../components/models/json-api/application/application.yaml#/JsonApiModel_application_type'
          id:
            $ref: '../../../components/models/json-api/application/application.yaml#/JsonApiModel_application_id'
          attributes:
            type: object
            additionalProperties: false
            properties:
              # relationship attributes
              status:
                $ref: '../../../components/models/json-api/application/status.yaml#/JsonApiModel_application-status_relationship_attribute'
            required:
              - status
          relationships:
            type: object
            additionalProperties: false
            properties:
              job:
                $ref: '../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_relationship'
              latestEvent:
                $ref: '../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_relationship'
            required:
              - job
              - latestEvent
        required:
          - type
          - id
          - attributes
          - relationships
    included:
      type: array
      items:
        anyOf:
          - $ref: '#/Response_applications_includedJob_teacher'
          - $ref: '#/Response_applications_includedSchool_teacher'
          - $ref: '#/Response_applications_includedApplicationEvent_teacher'
  required:
    - meta
    - schema
    - data
    - included

Response_applications_includedJob_teacher:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_type'
    id:
      $ref: '../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        title:
          $ref: '../../../components/models/library/job/job.yaml#/job_title'
      required:
        - title
    relationships:
      type: object
      additionalProperties: false
      properties:
        school:
          $ref: '../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_relationship'
      required:
        - school
  required:
    - type
    - id
    - attributes
    - relationships

Response_applications_includedSchool_teacher:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_type'
    id:
      $ref: '../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        name:
          $ref: '../../../components/models/library/school/school.yaml#/school_name'
        slug:
          $ref: '../../../components/models/library/school/school.yaml#/school_slug'
        #relationship attributes
        city:
          $ref: '../../../components/models/json-api/regional/city.yaml#/JsonApiModel_regional-city_relationship_attribute'
        smallProfilePhoto:
          $ref: '../../../components/models/json-api/general/photo.yaml#/JsonApiModel_general-photo_relationship_attribute'
      required:
        - name
        - slug
        - city
        - smallProfilePhoto
  required:
    - type
    - id
    - attributes

Response_applications_includedApplicationEvent_teacher:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_type'
    id:
      $ref: '../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        # simple attributes
        date:
          $ref: '../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_date'
        # relationship attributes
        type:
          $ref: '../../../components/models/json-api/application/eventType.yaml#/JsonApiModel_application-eventType_relationship_attribute'
      required:
        - date
        - type
  required:
    - type
    - id
    - attributes

# school
Response_applications_school:
  type: object
  additionalProperties: false
  properties:
    meta:
      $ref: '#/Response_applications_meta'
    schema:
      type: string
      enum:
        - admin
    data:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          type:
            $ref: '../../../components/models/json-api/application/application.yaml#/JsonApiModel_application_type'
          id:
            $ref: '../../../components/models/json-api/application/application.yaml#/JsonApiModel_application_id'
          attributes:
            type: object
            additionalProperties: false
            properties:
              # simple attributes
              creationDate:
                $ref: '../../../components/models/library/application/application.yaml#/application_creationDate'
              latestUpdateDate:
                $ref: '../../../components/models/library/application/application.yaml#/application_latestUpdateDate'
              # relationship attributes
              status:
                $ref: '../../../components/models/json-api/application/status.yaml#/JsonApiModel_application-status_relationship_attribute'
          relationships:
            type: object
            additionalProperties: false
            properties:
              job:
                $ref: '../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_relationship'
              teacher:
                $ref: '../../../components/models/json-api/teacher/teacher.yaml#/JsonApiModel_teacher_relationship'
              latestEvent:
                $ref: '../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_relationship'
        required:
          - type
          - id
          - attributes
          - relationships
    included:
      type: array
      items:
        anyOf:
          - $ref: '#/Response_applications_includedTeacher_school'
          - $ref: '#/Response_applications_includedJob_school'
          - $ref: '#/Response_applications_includedSchool_school'
          - $ref: '#/Response_applications_includedApplicationEvent_school'
  required:
    - meta
    - schema
    - data
    - included

Response_applications_includedTeacher_school:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '../../../components/models/json-api/teacher/teacher.yaml#/JsonApiModel_teacher_type'
    id:
      $ref: '../../../components/models/json-api/teacher/teacher.yaml#/JsonApiModel_teacher_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        memberNumber:
          $ref: '../../../components/models/library/teacher/teacher.yaml#/teacher_memberNumber'
        # TODO: consider replacing with user relationship attribute
        fullName:
          $ref: '../../../components/models/library/teacher/teacher.yaml#/teacher_fullName'
        # TODO: consider replacing with photo relationship attribute
        profilePhotoUrl:
          $ref: '../../../components/models/library/teacher/teacher.yaml#/teacher_profilePhotoUrl'
  required:
    - type
    - id
    - attributes

Response_applications_includedJob_school:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_type'
    id:
      $ref: '../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        title:
          $ref: '../../../components/models/library/job/job.yaml#/job_title'
    relationships:
      type: object
      additionalProperties: false
      properties:
        school:
          $ref: '../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_relationship'
  required:
    - type
    - id
    - attributes
    - relationships

Response_applications_includedSchool_school:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_type'
    id:
      $ref: '../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        # simple attributes
        name:
          $ref: '../../../components/models/library/school/school.yaml#/school_name'
        slug:
          $ref: '../../../components/models/library/school/school.yaml#/school_slug'
        # relationship attributes
        city:
          $ref: '../../../components/models/json-api/regional/city.yaml#/JsonApiModel_regional-city_relationship_attribute'
      required:
        - name
        - slug
        - city
  required:
    - type
    - id
    - attributes

Response_applications_includedApplicationEvent_school:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_type'
    id:
      $ref: '../../../components/models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        # simple attributes
        date:
          $ref: '../../../components/models/library/application/applicationEvent.yaml#/application-applicationEvent_date'
        # relationship attributes
        type:
          $ref: '../../../components/models/json-api/application/eventType.yaml#/JsonApiModel_application-eventType_relationship_attribute'
      required:
        - date
        - type
  required:
    - type
    - id
    - attributes
