Response_application-applicationDataIssues:
  oneOf:
    - $ref: "#/Response_application-applicationDataIssues_admin"
    - $ref: "#/Response_application-applicationDataIssues_admin-v2"
  discriminator:
    propertyName: schema
    mapping:
      admin: "#/Response_application-applicationDataIssues_admin"
      admin-v2: "#/Response_application-applicationDataIssues_admin-v2"

# admin (non-standard, deprecated)
Response_application-applicationDataIssues_admin:
  type: object
  additionalProperties: false
  properties:
    # property isn't returned by API call, but this is need here for openapi to work
    schema:
      deprecated: true
      type: string
      enum:
        - admin
    data:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          type:
            $ref: "../../../components/models/json-api/application/applicationDataIssue.yaml#/JsonApiModel_application-applicationDataIssue_type"
          id:
            $ref: "../../../components/models/json-api/application/applicationDataIssue.yaml#/JsonApiModel_application-applicationDataIssue_id"
          attributes:
            type: object
            additionalProperties: false
            properties:
              # errors due to this spec being non-standard
              name:
                type: string
                description: Name of the related guideline (non-standard json-api)
            required:
              - name
        required:
          - type
          - id
          - attributes
  required:
    # errors due to this spec being non-standard
    - schema
    - data

# admin-v2
Response_application-applicationDataIssues_admin-v2:
  type: object
  additionalProperties: false
  properties:
    schema:
      type: string
      enum:
        - admin-v2
    data:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          type:
            $ref: "../../../components/models/json-api/application/applicationDataIssue.yaml#/JsonApiModel_application-applicationDataIssue_type"
          id:
            $ref: "../../../components/models/json-api/application/applicationDataIssue.yaml#/JsonApiModel_application-applicationDataIssue_id"
          attributes:
            type: object
            additionalProperties: false
            properties:
              date:
                $ref: "../../../components/models/library/application/applicationDataIssue.yaml#/application-applicationDataIssue_date"
            required:
              - date
          relationships:
            type: object
            additionalProperties: false
            properties:
              # application:
              #   $ref: "../../../components/models/json-api/application/application.yaml#/JsonApiModel_application_relationship"
              guideline:
                $ref: "../../../components/models/json-api/application/guideline.yaml#/JsonApiModel_application-guideline_relationship"
            required:
              # - application
              - guideline
        required:
          - type
          - id
          - attributes
          - relationships
    included:
      type: array
      items:
        anyOf:
          - $ref: "#/Response_application-applicationDataIssues_includedGuideline_admin-v2"
  required:
    - schema
    - data
    - included

Response_application-applicationDataIssues_includedGuideline_admin-v2:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: "../../../components/models/json-api/application/applicationDataIssue.yaml#/JsonApiModel_application-applicationDataIssue_type"
    id:
      $ref: "../../../components/models/json-api/application/applicationDataIssue.yaml#/JsonApiModel_application-applicationDataIssue_id"
    attributes:
      type: object
      additionalProperties: false
      properties:
        name:
          $ref: "../../../components/models/library/application/guideline.yaml#/application-guideline_name"
      required:
        - name
  required:
    - type
    - id
    - attributes
