get:
  operationId: getLists_jobApplications
  tags:
    - lists-not-jsonapi
  summary: Get job applications
  #parameters:

  responses:
    "200":
      description: successful operation
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/current/lists/job-application-list.yaml"
    "400":
      description: Invalid ID supplied
    "404":
      description: Pet not found
  security:
    - api_key: []
#parameters - none
