get:
  operationId: getLists_jobApplications_current
  tags:
    - lists
    - status-current
  summary: Get job applications (current)
  #parameters:

  responses:
    "200":
      description: successful operation
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/current/lists/job-application-list.yaml"
    "400":
      description: Invalid ID supplied
    "404":
      description: Pet not found
  security:
    - api_key: []
#parameters - none
