get:
  operationId: getApplications
  tags:
    - applications
    - status-proposed
  summary: Get list of 20 applications
  description: |
    - Admin: Can see all applications and all related events
    - Teacher: Can see only applications which relate to them, and all related events
    - School: Can see only applications which have been submitted to them, and only events from that point onwards
  parameters:
    - in: query
      name: schema
      required: true
      schema:
        type: string
        enum:
          - admin
          - school
          - teacher
    - in: query
      name: filter
      style: deepObject
      allowReserved: true
      explode: true
      schema:
        type: object
        properties:
          filter[id][contains]:
            type: number
          filter[status.id][contains]:
            type: number
        example:
          id][contains: 1
          status.id][contains: 1
    - in: query
      name: page
      style: deepObject
      allowReserved: true
      explode: true
      schema:
        type: object
        properties:
          page[number]:
            type: number
          page[size]:
            type: number
        example:
          number: 1
          size: 1
    - in: query
      name: sort
      example: -creationDate
  responses:
    "200":
      description: OK (Request successful)
      content:
        application/json:
          schema:
            $ref: "../../../components/responses/proposed/applications.yaml#/ApplicationsResponse"
    "400":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_400"
    "401":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_401"
    "403":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_403"
    "404":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_404"
    "413":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_413"
    "422":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_422"
  security:
    - api_key: []

post:
  operationId: postApplication
  summary: Create application
  tags:
    - applications
  description: ""
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            data:
              type: object
              properties:
                type:
                  type: string
                  example: application
                attributes:
                  allOf:
                    - type: object
                      properties:
                        job:
                          $ref: "../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_relationship_attribute"
                        memberNumber:
                          $ref: "../../../components/models/library/teacher/teacher.yaml#/teacher_memberNumber"
                    - required:
                        - job
                        - memberNumber
  responses:
    "201":
      description: CREATED (Request successful)
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  type:
                    type: string
                    example: Application
                  id:
                    type: string
                    example: "2"
    "400":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_400"
    "401":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_401"
    "403":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_403"
    "404":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_404"
    "413":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_413"
    "422":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_422"
