get:
  operationId: getApplication
  tags:
    - applications
    - status-proposed
  summary: Get an application (proposed)
  parameters:
    - in: path
      name: applicationId
      required: true
      example: 12
      schema:
        type: integer
        format: int32
    - in: query
      name: schema
      required: true
      schema:
        type: string
        enum:
          - admin
          - school
          - teacher
    - in: query
      name: fields
      style: deepObject
      allowReserved: true
      explode: true
      schema:
        type: object
        additionalProperties:
          $ref: "../../../components/models/library/application/application.yaml#/application_standardProperties_all"
          # $ref: "../../../components/schemas/proposed/simple-models/Application.yaml#/ApplicationProperties_all"
        example:
          application: name,slug,locationLatLong
  responses:
    "200":
      description: successful operation
      content:
        application/json:
          schema:
            $ref: "../../../components/responses/proposed/application.yaml#/ApplicationResponse"
    "400":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_400"
    "401":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_401"
    "404":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_404"
  security:
    - api_key: []

patch:
  description: Update Application
  operationId: patchApplication
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            type:
              type: string
              example: application
            attributes:
              allOf:
                - type: object
                - $ref: "../../../components/models/library/application/application.yaml#/application_filter_additionalProperties"

  responses:
    "204":
      content:
        application/json:
          schema:
            type: object
            default: null
      description: Item Updated
  summary: Update application (proposed)
  tags:
    - applications
