get:
  operationId: getApplications
  tags:
    - applications
    - status-proposed
  summary: Get list of 20 applications (proposed)
  parameters:
    - in: query
      name: schema
      required: true
      schema:
        type: string
        enum:
          - admin
          - school
          - teacher
    - in: query
      name: filter
      style: deepObject
      allowReserved: true
      explode: true
      schema:
        type: object
        additionalProperties:
          $ref: "../../../components/models/library/application/application.yaml#/application_metaProperties_shared"
          # $ref: "../../../components/schemas/proposed/simple-models/Application.yaml#/ApplicationProperties_all"
        example:
          application: application id, school name, job id
  responses:
    "200":
      description: OK (Request successful)
      content:
        application/json:
          schema:
            $ref: "../../../components/responses/proposed/applications.yaml#/ApplicationsResponse"
    "400":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_400"
    "401":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_401"
    "403":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_403"
    "404":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_404"
    "413":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_413"
    "422":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_422"
  security:
    - api_key: []

post:
  description: ""
  operationId: postApplication
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            data:
              type: object
              properties:
                type:
                  type: string
                  example: application
                attributes:
                  allOf:
                    - type: object
                      $ref: "../../../components/models/library/application/application.yaml#/application_metaProperties_shared"
                    - required:
                        - job
                        - memberNumber
  responses:
    "201":
      description: CREATED (Request successful)
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  type:
                    type: string
                    example: Application
                  id:
                    type: string
                    example: "2"
    "400":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_400"
    "401":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_401"
    "403":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_403"
    "404":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_404"
    "413":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_413"
    "422":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_422"
  summary: Create application (proposed)
  tags:
    - applications
