get:
  operationId: getApplicationDataIssues
  tags:
    - applications
    - status-proposed
  summary: Get application data issue
  parameters:
    - in: query
      name: filter
      style: deepObject
      allowReserved: true
      explode: true
      schema:
        # type: object
        # additionalProperties:
        type: object
        properties:
          filter[application.id]:
            type: number
            example: 1
            description: Required unless schema is 'admin-allApplications'
          filter[application.teacher.memberNumber]:
            type: number
            example: 123456
            description: Required if schema is 'admin-allApplications'
        example:
          application.id: 1
          application.teacher.memberNumber: 1

  responses:
    "200":
      description: OK (Request successful)
      content:
        application/json:
          schema:
            $ref: "../../../components/responses/proposed/applicationDataIssues.yaml#/Application-applicationDataIssuesResponse"
    "400":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_400"
    "401":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_401"
    "403":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_403"
    "404":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_404"
    "413":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_413"
    "422":
      $ref: "../../../components/models/json-api/error/Error.yaml#/JsonApiModel_error_422"
  security:
    - api_key: []
