JsonApiModel_system-environment:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '#/JsonApiModel_system-environment_type'
    id:
      $ref: '#/JsonApiModel_system-environment_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        # simple attributes
        staticUrlPathStub:
          $ref: '../../library/system/environment.yaml#/system-environment_staticUrlPathStub'
  required:
    - type
    - id
    - attributes

JsonApiModel_system-environment_type:
  type: string
  example: system-environment
  description: Unique identifier of the entity type
  readOnly: true

JsonApiModel_system-environment_id:
  type: string
  example: '555'
  readOnly: true
  description: Unique identifier of the entity (string)

JsonApiModel_system-environment_relationship:
  type: object
  description: |
    [Simple model](/#tag/simple-model-system-environment) | 
    [JSON:API model](/#tag/json-api-model-system-environment)
  additionalProperties: false
  properties:
    data:
      type: object
      additionalProperties: false
      properties:
        type:
          $ref: '#/JsonApiModel_system-environment_type'
        id:
          $ref: '#/JsonApiModel_system-environment_id'
      required:
        - type
        - id
  required:
    - data

JsonApiModel_system-environment_includedResponse_default:
  type: object
  additionalProperties: false
  properties:
    type:
      $ref: '#/JsonApiModel_system-environment_type'
    id:
      $ref: '#/JsonApiModel_system-environment_id'
    attributes:
      type: object
      additionalProperties: false
      properties:
        # simple attributes
        staticUrlPathStub:
          $ref: '../../library/system/environment.yaml#/system-environment_staticUrlPathStub'
      required:
        - staticUrlPathStub
  required:
    - type
    - id
    - attributes
