type: object
properties:
  statusId: 
    type: integer
    format: int32
    example: 419
  applicationDate: 
    type: integer
    format: int64
    example: 1550416230000
  name:
    type: string
  job:
    $ref: '../../jobs/JobSet1.yaml'
  school:
    $ref: '../../schools/SchoolSet1.yaml'
