get:
  operationId: getJobApplication_current
  tags:
    - job applications
    - status-current
  summary: Get list of job applications (current)
  responses:
    "200":
      description: successful operation
      content:
        application/json:
          schema:
            $ref: "../../../components/schemas/current/job-applications/applications-search.yaml"
    "400":
      description: Invalid ID supplied
    "404":
      description: Pet not found
  security:
    - api_key: []
# parameters
#     @RequestParam(value="job-subjects",required = false) String[] _subjects
# , @RequestParam(value="job-positions",required = false) String[] _positions
# , @RequestParam(value="application-statuses",required = false) String[] _jobApplicationStatuses
# , @RequestParam(value="job-ids",required = false) Integer[] jobIds
# , @RequestParam(value="school-ids",required = false) Integer[] schoolIds
# , @RequestParam(value="member-numbers",required = false) Integer[] memberNumbers
# , @RequestParam(value="teacher-ids",required = false) Integer[] teacherIds
# , @RequestParam(value="action-by-ids",required = false) Integer[] actionByUserIds
# , @RequestParam(value="minimum-th-placeability-rating",required = false) Integer thPlaceabilityRating
#   , @RequestParam(value="page-size",required = false) Integer pagesize
# , @RequestParam(value="page-number",required=false) Integer pagenumber
