Application-applicationDataIssuesResponse:
  type: object
  properties:
    schema:
      type: string
      example: admin
      enum:
        - admin
  discriminator:
    propertyName: schema
    mapping:
      admin: "#/Application-applicationDataIssues_admin"
  required:
    - schema

# admin
Application-applicationDataIssues_admin:
  allOf:
    - $ref: "#/Application-applicationDataIssuesResponse"
    - properties:
        data:
          type: object
          properties:
            type:
              $ref: "../../../components/models/json-api/application/applicationDataIssue.yaml#/JsonApiModel_application-applicationDataIssue_type"
            id:
              $ref: "../../../components/models/json-api/application/applicationDataIssue.yaml#/JsonApiModel_application-applicationDataIssue_id"
            attributes:
              type: object
              properties:
                date:
                  $ref: "../../../components/models/library/application/applicationDataIssue.yaml#/application-applicationDataIssue_date"
              required:
                - date
            relationships:
              type: object
              properties:
                applicationId:
                  $ref: "../../../components/models/json-api/application/application.yaml#/JsonApiModel_application_relationship"
                guidelineId:
                  $ref: "../../../components/models/json-api/user/user.yaml#/JsonApiModel_user_relationship"
              required:
                - application
                - guideline
          required:
            - type
            - id
            - attributes
            - relationships
