ApplicationResponse:
  type: object
  properties:
    data:
      type: array
      items:
        type: object
        properties:
          type:
            type: string
            example: application
          id:
            type: string
            example: "123"
          attributes:
            type: object
            properties:
              thMatchType:
                type: object
                properties:
                  id:
                    type: string
                    example: "2"
              status:
                type: object
                properties:
                  id:
                    type: string
                    example: "1"
                  latestUpdateDate:
                    type: string
                    example: 2011-02-07T15:53:34:000Z 
              recommendationText:
                type: string
                example: Foo bar
          relationships:
            type: object
            properties:
              job:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      type:
                        type: string
                        example: job
                      id:
                        type: string
                        example: "22"
              teacher:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      type:
                        type: string
                        example: teacher
                      id:
                        type: string
                        example: "33"
    included:
      type: array
      items:
        type: object
        properties:
          type:
            type: string
            example: job
          id:
            type: string
            example: "22"
          attributes:
            type: object
            properties:
              title:
                type: string
                example: Humanities Teacher - Shenzhen campus (February 2022)
              thOwnerUser:
                type: object
                properties:
                  id:
                    type: string
                    example: "234"
              subject:
                type: object
                properties:
                  id:
                    type: string
                    example: "1"
              role:
                type: object
                properties:
                  id:
                    type: string
                    example: "1"
                    latestUpdateDate:
                     type: string
                     example: 2011-02-07T00:00:00Z
                    status:
                     type: object
                     properties:
                      id:
                       type: string
                       example: "1"
          relationships:
            type: object
            properties:
              school:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      type:
                        type: string
                        example: school
                      id:
                        type: string
                        example: "225"
        attributes:  
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                example: teacher 
              id:
                type: string
                example: 33       
                attributes:  
                  type: array
                  items:
                    type: object
                    properties:
                      memberNumber:
                        type: string
                        example: 1314160   
          attributes:  
           type: array
           items:
            type: object
            properties:
              type:
                type: string
                example: school        
              attributes:  
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        example: Maple Leaf International School 
                      city:
                        type: object
                        properties:
                          type:
                            id: string
                            example: 2256
                      lraUser:
                        type: object
                        properties:
                          type:
                            id: string
                            example: 123