ApplicationResponse:
  type: object
  properties:
    schema:
      type: string
      example: admin
      enum:
        - admin
        - school
        - teacher
  discriminator:
    propertyName: schema
    mapping:
      admin: "#/ApplicationResponse_admin"
      teacher: "#/ApplicationResponse_teacher"
  required:
    - schema

# admin
ApplicationResponse_admin:
  allOf:
    - $ref: "#/ApplicationResponse"
    - properties:
        data:
          type: object
          properties:
            type:
              $ref: "../../../components/models/json-api/application/application.yaml#/JsonApiModel_application_type"
            id:
              $ref: "../../../components/models/json-api/application/application.yaml#/JsonApiModel_application_id"
            attributes:
              type: object
              properties:
                # relationship attributes
                thMatchType:
                  $ref: "../../../components/models/library/application/application.yaml#/application_thMatchTypeId"
              # allOf:
              #   - $ref: "../../../components/models/library/application/application.yaml#/application_attributes_admin"
              #   - $ref: "../../../components/models/library/application/application.yaml#/application_properties_status"
              #   - $ref: "../../../components/models/library/application/application.yaml#/application_properties_thMatchType"
            relationships:
              type: object
              properties:
                job:
                  $ref: "../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_relationship"
                teacher:
                  $ref: "../../../components/models/json-api/teacher/teacher.yaml#/JsonApiModel_teacher_relationship"
                # latestEvent:
                #   $ref: "../../../components/models/json-api/application/ApplicationEvent.yaml#/JsonApiModel_application-applicationEvent_relationship"
        included:
          type: array
          items:
            anyOf:
              - $ref: "#/ApplicationResponse_includedSchool_admin"
              - $ref: "#/ApplicationResponse_includedJob_admin"
              - $ref: "#/ApplicationResponse_includedTeacher_admin"

ApplicationResponse_includedTeacher_admin:
  type: object
  properties:
    type:
      $ref: "../../../components/models/json-api/teacher/teacher.yaml#/JsonApiModel_teacher_type"
    id:
      $ref: "../../../components/models/json-api/teacher/teacher.yaml#/JsonApiModel_teacher_id"
    attributes:
      type: object
      properties:
        memberNumber:
          $ref: "../../../components/models/library/teacher/teacher.yaml#/teacher_memberNumber"

ApplicationResponse_includedJob_admin:
  type: object
  properties:
    type:
      $ref: "../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_type"
    id:
      $ref: "../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_id"
    attributes:
      type: object
      properties:
        title:
          $ref: "../../../components/models/library/job/job.yaml#/job_title"
        startDate:
          $ref: "../../../components/models/library/job/job.yaml#/job_startDate"
        thOwnerUser:
          $ref: "../../../components/models/library/job/job.yaml#/job_thOwnerUser"
        status:
          $ref: "../../../components/models/library/job/job.yaml#/job_status"
        subject:
          $ref: "../../../components/models/library/job/job.yaml#/job_subject"
        role:
          $ref: "../../../components/models/library/job/job.yaml#/job_role"
    relationships:
      type: object
      properties:
        school:
          $ref: "../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_relationship"

ApplicationResponse_includedSchool_admin:
  type: object
  properties:
    type:
      $ref: "../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_type"
    id:
      $ref: "../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_id"
    attributes:
      type: object
      properties:
        name:
          $ref: "../../../components/models/library/school/school.yaml#/school_name"
        thRating:
          $ref: "../../../components/models/library/school/school.yaml#/school_thRating"
        slug:
          $ref: "../../../components/models/library/school/school.yaml#/school_slug"
        city:
          $ref: "../../../components/models/library/school/school.yaml#/school_city"
        lraUser:
          $ref: "../../../components/models/library/school/school.yaml#/school_lraUser"
      required:
        - name
        - slug
        - city

# teacher
ApplicationResponse_teacher:
  allOf:
    - $ref: "#/ApplicationResponse"
    - properties:
        data:
          type: object
          properties:
            type:
              $ref: "../../../components/models/json-api/application/application.yaml#/JsonApiModel_application_type"
            id:
              $ref: "../../../components/models/json-api/application/application.yaml#/JsonApiModel_application_id"
            attributes:
              allOf:
                - $ref: "../../../components/models/library/application/application.yaml#/application_attributes_teacher"
                - $ref: "../../../components/models/library/application/application.yaml#/application_properties_status"
            relationships:
              type: object
              properties:
                job:
                  $ref: "../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_relationship"
        included:
          type: array
          items:
            anyOf:
              - $ref: "#/ApplicationResponse_includedSchool_teacher"
              - $ref: "#/ApplicationResponse_includedJob_teacher"

ApplicationResponse_includedJob_teacher:
  type: object
  properties:
    type:
      $ref: "../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_type"
    id:
      $ref: "../../../components/models/json-api/job/job.yaml#/JsonApiModel_job_id"
    attributes:
      type: object
      properties:
        title:
          $ref: "../../../components/models/library/job/job.yaml#/job_title"
        startDate:
          $ref: "../../../components/models/library/job/job.yaml#/job_startDate"
        thOwnerUser:
          $ref: "../../../components/models/library/job/job.yaml#/job_thOwnerUser"
        status:
          $ref: "../../../components/models/library/job/job.yaml#/job_status"
        subject:
          $ref: "../../../components/models/library/job/job.yaml#/job_subject"
        role:
          $ref: "../../../components/models/library/job/job.yaml#/job_role"
    relationships:
      type: object
      properties:
        school:
          $ref: "../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_relationship"

ApplicationResponse_includedSchool_teacher:
  type: object
  properties:
    type:
      $ref: "../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_type"
    id:
      $ref: "../../../components/models/json-api/school/school.yaml#/JsonApiModel_school_id"
    attributes:
      type: object
      properties:
        name:
          $ref: "../../../components/models/library/school/school.yaml#/school_name"
        slug:
          $ref: "../../../components/models/library/school/school.yaml#/school_slug"
        city:
          $ref: "../../../components/models/library/school/school.yaml#/school_city"
        smallProfileImageUrl:
          $ref: "../../../components/models/library/school/school.yaml#/school_smallProfileImageUrl"
