application-applicationEventResponse:
  type: object
  properties:
    data:
      type: array
      items:
        type: object
        properties:
          type:
            $ref: "../../models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_type"
          id:
            $ref: "../../models/json-api/application/applicationEvent.yaml#/JsonApiModel_application-applicationEvent_id"
          attributes:
            type: object
            allOf:
              - $ref: "../../models/library/application/applicationEvent.yaml#/application-applicationEvent_standardProperties_all"
          relationships:
            type: object
            properties:
              creationUser:
                $ref: "../../models/json-api/user/user.yaml#/JsonApiModel_user_relationship"
              latestUpdateUser:
                $ref: "../../models/json-api/user/user.yaml#/JsonApiModel_user_relationship"
    included:
      type: array
      items:
        type: object
        properties:
          type:
            $ref: "../../models/json-api/user/user.yaml#/JsonApiModel_user_type"
          id:
            $ref: "../../models/json-api/user/user.yaml#/JsonApiModel_user_id"
          attributes:
            type: object
            properties:
              fullName:
                $ref: "../../models/json-api/user/user.yaml#/JsonApiModel_user_fullName"
# consider having a 'rule' that says every property should be a reference to the library (rule A, say)
