get:
  operationId: getJobApplications
  tags:
    - job-applications-no-longer-in-use
  summary: Get job applications
  responses:
    "200":
      description: successful operation
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/current/job-applications/job-application-search.yaml"
    "400":
      description: Invalid ID supplied
    "404":
      description: Pet not found
  security:
    - api_key: []
#parameters - none
